const VOCABULARY_DATA = [
  {
    id: 'animals',
    name: 'Animals',
    icon: '🐾',
    difficulty: 1,
    description: 'Learn names of common animals',
    words: [
      { word: 'cat', definition: 'a small furry pet that purrs', example: 'The cat is sleeping on the sofa.', phonetic: '/kæt/', pos: 'noun', difficulty: 1, synonyms: ['kitten', 'feline'] },
      { word: 'dog', definition: 'a pet that barks and wags its tail', example: 'I walk my dog every morning.', phonetic: '/dɒɡ/', pos: 'noun', difficulty: 1, synonyms: ['puppy', 'canine'] },
      { word: 'elephant', definition: 'a very large animal with a trunk and tusks', example: 'The elephant splashes water with its trunk.', phonetic: '/ˈelɪfənt/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'lion', definition: 'a large wild cat that lives in Africa', example: 'The lion is called the king of the jungle.', phonetic: '/ˈlaɪən/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'tiger', definition: 'a large orange wild cat with black stripes', example: 'Tigers are very strong swimmers.', phonetic: '/ˈtaɪɡər/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'bear', definition: 'a large strong animal with thick fur', example: 'The bear catches fish in the river.', phonetic: '/beər/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'bird', definition: 'an animal with wings and feathers that can fly', example: 'The bird sings a beautiful song.', phonetic: '/bɜːrd/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'fish', definition: 'an animal that lives in water and has gills', example: 'My fish swims around its tank all day.', phonetic: '/fɪʃ/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'horse', definition: 'a large animal people can ride', example: 'She loves to ride her horse in the field.', phonetic: '/hɔːrs/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'monkey', definition: 'a clever animal that lives in trees', example: 'The monkey eats a banana for lunch.', phonetic: '/ˈmʌŋki/', pos: 'noun', difficulty: 1, synonyms: ['ape'] },
      { word: 'rabbit', definition: 'a small furry animal with long ears', example: 'The rabbit hops across the garden.', phonetic: '/ˈræbɪt/', pos: 'noun', difficulty: 1, synonyms: ['bunny'] },
      { word: 'sheep', definition: 'a farm animal with thick woolly fur', example: 'The sheep graze in the green field.', phonetic: '/ʃiːp/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'cow', definition: 'a large farm animal that gives milk', example: 'The cow chews grass in the meadow.', phonetic: '/kaʊ/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'frog', definition: 'a small green animal that jumps and croaks', example: 'The frog jumps from lily pad to lily pad.', phonetic: '/frɒɡ/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'duck', definition: 'a water bird with a flat bill and webbed feet', example: 'The duck swims across the pond.', phonetic: '/dʌk/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'chicken', definition: 'a farm bird that lays eggs', example: 'The chicken pecks at the ground for food.', phonetic: '/ˈtʃɪkɪn/', pos: 'noun', difficulty: 1, synonyms: ['hen'] },
      { word: 'pig', definition: 'a pink farm animal with a curly tail', example: 'The pig rolls in the mud to stay cool.', phonetic: '/pɪɡ/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'snake', definition: 'a long reptile with no legs', example: 'The snake slithers through the grass.', phonetic: '/sneɪk/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'turtle', definition: 'a slow reptile with a hard shell on its back', example: 'The turtle hides inside its shell.', phonetic: '/ˈtɜːrtl/', pos: 'noun', difficulty: 2, synonyms: ['tortoise'] },
      { word: 'whale', definition: 'the largest animal in the ocean', example: 'The whale jumps out of the water.', phonetic: '/weɪl/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'dolphin', definition: 'a smart ocean animal that is friendly to people', example: 'The dolphin swims and jumps for joy.', phonetic: '/ˈdɒlfɪn/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'parrot', definition: 'a colorful bird that can talk', example: 'The parrot says hello to everyone.', phonetic: '/ˈpærət/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'panda', definition: 'a black and white bear from China', example: 'The panda eats bamboo every day.', phonetic: '/ˈpændə/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'kangaroo', definition: 'an Australian animal that jumps with big back legs', example: 'The kangaroo carries its baby in a pouch.', phonetic: '/ˌkæŋɡəˈruː/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'owl', definition: 'a bird that stays awake at night', example: 'The owl hunts for mice when it is dark.', phonetic: '/aʊl/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'fox', definition: 'a small wild animal with a bushy tail', example: 'The fox is very clever and quick.', phonetic: '/fɒks/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'deer', definition: 'a graceful wild animal with antlers', example: 'The deer runs through the forest quickly.', phonetic: '/dɪər/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'mouse', definition: 'a tiny animal with a long tail and whiskers', example: 'The mouse nibbles on a piece of cheese.', phonetic: '/maʊs/', pos: 'noun', difficulty: 1, synonyms: ['rodent'] },
      { word: 'squirrel', definition: 'a small animal with a big fluffy tail that collects nuts', example: 'The squirrel hides acorns for the winter.', phonetic: '/ˈskwɜːrəl/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'bee', definition: 'a flying insect that makes honey', example: 'The bee buzzes from flower to flower.', phonetic: '/biː/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'butterfly', definition: 'a flying insect with colorful wings', example: 'The butterfly lands gently on the flower.', phonetic: '/ˈbʌtərflaɪ/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'ant', definition: 'a tiny insect that works very hard', example: 'The ant carries food back to its home.', phonetic: '/ænt/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'spider', definition: 'a small eight-legged animal that makes webs', example: 'The spider spins a beautiful web.', phonetic: '/ˈspaɪdər/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'wolf', definition: 'a wild animal that howls and lives in a pack', example: 'The wolf howls at the full moon.', phonetic: '/wʊlf/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'goat', definition: 'a farm animal with horns that climbs well', example: 'The goat climbs up the steep mountain.', phonetic: '/ɡoʊt/', pos: 'noun', difficulty: 1, synonyms: [] },
      { word: 'donkey', definition: 'a gray animal like a small horse with long ears', example: 'The donkey carries heavy loads.', phonetic: '/ˈdɒŋki/', pos: 'noun', difficulty: 2, synonyms: ['mule'] },
      { word: 'camel', definition: 'a desert animal with one or two humps', example: 'The camel travels across the hot desert.', phonetic: '/ˈkæml/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'hippo', definition: 'a very large African animal that lives in rivers', example: 'The hippo opens its big mouth wide.', phonetic: '/ˈhɪpoʊ/', pos: 'noun', difficulty: 2, synonyms: ['hippopotamus'] },
      { word: 'rhino', definition: 'a large animal with a horn on its nose', example: 'The rhino charges through the grassland.', phonetic: '/ˈraɪnoʊ/', pos: 'noun', difficulty: 3, synonyms: ['rhinoceros'] },
      { word: 'giraffe', definition: 'a very tall animal with a long neck', example: 'The giraffe eats leaves from the top of the tree.', phonetic: '/dʒɪˈræf/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'zebra', definition: 'a black and white striped horse from Africa', example: 'The zebra runs across the savannah.', phonetic: '/ˈzebrə/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'penguin', definition: 'a black and white bird that swims but cannot fly', example: 'The penguin waddles on the ice.', phonetic: '/ˈpeŋɡwɪn/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'eagle', definition: 'a large strong bird that hunts small animals', example: 'The eagle soars high in the sky.', phonetic: '/ˈiːɡl/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'swan', definition: 'a large white water bird with a long neck', example: 'The swan glides gracefully on the lake.', phonetic: '/swɒn/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'crocodile', definition: 'a large dangerous reptile that lives in rivers', example: 'The crocodile waits quietly in the water.', phonetic: '/ˈkrɒkədaɪl/', pos: 'noun', difficulty: 3, synonyms: ['alligator'] },
      { word: 'bat', definition: 'a flying animal that comes out at night', example: 'The bat sleeps upside down in the cave.', phonetic: '/bæt/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'hedgehog', definition: 'a small animal with spikes on its back', example: 'The hedgehog curls into a spiky ball.', phonetic: '/ˈhedʒhɒɡ/', pos: 'noun', difficulty: 3, synonyms: [] },
      { word: 'octopus', definition: 'a sea animal with eight arms', example: 'The octopus changes color to hide.', phonetic: '/ˈɒktəpəs/', pos: 'noun', difficulty: 3, synonyms: [] },
      { word: 'shark', definition: 'a large dangerous fish with sharp teeth', example: 'The shark swims fast through the ocean.', phonetic: '/ʃɑːrk/', pos: 'noun', difficulty: 2, synonyms: [] },
      { word: 'polar bear', definition: 'a large white bear that lives in the Arctic', example: 'The polar bear hunts seals on the ice.', phonetic: '/ˈpoʊlər beər/', pos: 'noun', difficulty: 3, synonyms: [] },
    ],
    collocations: [
      { phrase: 'a loyal dog', meaning: 'a dog that is faithful and friendly' },
      { phrase: 'a wild animal', meaning: 'an animal that lives in nature' },
      { phrase: 'a farm animal', meaning: 'an animal raised on a farm' },
      { phrase: 'a pet cat', meaning: 'a cat that lives with people' },
    ],
    quizQuestions: [
      { type: 'mcq', question: 'Which animal has a trunk?', options: ['Elephant', 'Lion', 'Tiger', 'Bear'], answer: 0, points: 10 },
      { type: 'mcq', question: 'What does a dog do?', options: ['Moo', 'Bark', 'Quack', 'Roar'], answer: 1, points: 10 },
      { type: 'fill', question: 'A ___ lives in water and has gills.', answer: 'fish', points: 15 },
      { type: 'mcq', question: 'Which animal has black and white stripes?', options: ['Giraffe', 'Zebra', 'Leopard', 'Cheetah'], answer: 1, points: 10 },
      { type: 'fill', question: 'A large orange cat with black stripes is a ___.', answer: 'tiger', points: 15 },
      { type: 'mcq', question: 'Which animal can fly?', options: ['Fish', 'Bird', 'Snake', 'Turtle'], answer: 1, points: 10 },
      { type: 'match', question: 'Match: Crocodile', pairs: [{ word: 'Crocodile', def: 'Large reptile with sharp teeth' }, { word: 'Butterfly', def: 'Insect with colorful wings' }], points: 20 },
      { type: 'sentence', question: 'Arrange: [is] [The] [cat] [sleeping]', answer: 'The cat is sleeping', points: 20 },
    ]
  },
  {
    id: 'colors',
    name: 'Colors',
    icon: '🎨',
    difficulty: 1,
    description: 'Learn the names of colors',
    words: [
      { word: 'red', definition: 'the color of strawberries and fire trucks', example: 'I have a red balloon.', phonetic: '/red/', pos: 'adjective', difficulty: 1 },
      { word: 'blue', definition: 'the color of the sky and the ocean', example: 'The sky is very blue today.', phonetic: '/bluː/', pos: 'adjective', difficulty: 1 },
      { word: 'green', definition: 'the color of grass and leaves', example: 'The frog is bright green.', phonetic: '/ɡriːn/', pos: 'adjective', difficulty: 1 },
      { word: 'yellow', definition: 'the color of the sun and bananas', example: 'The sun is yellow and warm.', phonetic: '/ˈjeloʊ/', pos: 'adjective', difficulty: 1 },
      { word: 'orange', definition: 'a color between red and yellow', example: 'The pumpkin is orange.', phonetic: '/ˈɒrɪndʒ/', pos: 'adjective', difficulty: 1 },
      { word: 'purple', definition: 'the color of grapes and lavender', example: 'She wore a purple dress.', phonetic: '/ˈpɜːrpl/', pos: 'adjective', difficulty: 1 },
      { word: 'pink', definition: 'a light red color', example: 'The flowers are pink.', phonetic: '/pɪŋk/', pos: 'adjective', difficulty: 1 },
      { word: 'black', definition: 'the darkest color, like the night sky', example: 'A black cat crossed the street.', phonetic: '/blæk/', pos: 'adjective', difficulty: 1 },
      { word: 'white', definition: 'the color of snow and milk', example: 'The rabbit is white and fluffy.', phonetic: '/waɪt/', pos: 'adjective', difficulty: 1 },
      { word: 'brown', definition: 'the color of chocolate and tree trunks', example: 'The bear has brown fur.', phonetic: '/braʊn/', pos: 'adjective', difficulty: 1 },
      { word: 'gray', definition: 'a color between black and white', example: 'The elephant is gray.', phonetic: '/ɡreɪ/', pos: 'adjective', difficulty: 1 },
      { word: 'gold', definition: 'a shiny yellow color like the metal', example: 'The medal is made of gold.', phonetic: '/ɡoʊld/', pos: 'adjective', difficulty: 2 },
      { word: 'silver', definition: 'a shiny gray-white color', example: 'The ring is silver.', phonetic: '/ˈsɪlvər/', pos: 'adjective', difficulty: 2 },
      { word: 'rainbow', definition: 'many colors in a curve across the sky', example: 'A rainbow appeared after the rain.', phonetic: '/ˈreɪnboʊ/', pos: 'noun', difficulty: 2 },
      { word: 'dark', definition: 'a color that has black in it', example: 'The room is very dark at night.', phonetic: '/dɑːrk/', pos: 'adjective', difficulty: 1 },
      { word: 'light', definition: 'a color with a lot of white in it', example: 'She painted the room light blue.', phonetic: '/laɪt/', pos: 'adjective', difficulty: 1 },
      { word: 'bright', definition: 'a strong and vivid color', example: 'The flowers are bright and cheerful.', phonetic: '/braɪt/', pos: 'adjective', difficulty: 2 },
      { word: 'colorful', definition: 'having many different colors', example: 'The parrot is very colorful.', phonetic: '/ˈkʌlərfl/', pos: 'adjective', difficulty: 2 },
      { word: 'pale', definition: 'a light color, not strong', example: 'She wore a pale blue shirt.', phonetic: '/peɪl/', pos: 'adjective', difficulty: 2 },
      { word: 'vibrant', definition: 'very bright and strong in color', example: 'The sunset was vibrant and beautiful.', phonetic: '/ˈvaɪbrənt/', pos: 'adjective', difficulty: 3 },
      { word: 'turquoise', definition: 'a blue-green color', example: 'The ocean is turquoise here.', phonetic: '/ˈtɜːrkwɔɪz/', pos: 'adjective', difficulty: 3 },
      { word: 'navy', definition: 'a very dark blue color', example: 'He wore a navy blue uniform.', phonetic: '/ˈneɪvi/', pos: 'adjective', difficulty: 2 },
      { word: 'coral', definition: 'a pink-orange color', example: 'The flowers are a beautiful coral.', phonetic: '/ˈkɔːrəl/', pos: 'adjective', difficulty: 3 },
      { word: 'ivory', definition: 'a creamy white color', example: 'The piano keys are ivory.', phonetic: '/ˈaɪvəri/', pos: 'adjective', difficulty: 3 },
      { word: 'maroon', definition: 'a dark red-brown color', example: 'She wore a maroon sweater.', phonetic: '/məˈruːn/', pos: 'adjective', difficulty: 3 },
      { word: 'lavender', definition: 'a pale purple color', example: 'The room was painted lavender.', phonetic: '/ˈlævəndər/', pos: 'adjective', difficulty: 3 },
      { word: 'lime', definition: 'a bright yellow-green color', example: 'The lime-green shirt is very bright.', phonetic: '/laɪm/', pos: 'adjective', difficulty: 3 },
      { word: 'indigo', definition: 'a deep blue-purple color', example: 'Indigo is between blue and purple.', phonetic: '/ˈɪndɪɡoʊ/', pos: 'adjective', difficulty: 3 },
      { word: 'violet', definition: 'a purple color, like the flower', example: 'Violet is a pretty color for a dress.', phonetic: '/ˈvaɪələt/', pos: 'adjective', difficulty: 2 },
      { word: 'beige', definition: 'a pale brown color', example: 'The sand is beige at the beach.', phonetic: '/beɪʒ/', pos: 'adjective', difficulty: 2 },
      { word: 'cream', definition: 'a very pale yellow-white color', example: 'She wore a cream-colored hat.', phonetic: '/kriːm/', pos: 'adjective', difficulty: 2 },
      { word: 'teal', definition: 'a dark greenish-blue color', example: 'The ocean water is teal.', phonetic: '/tiːl/', pos: 'adjective', difficulty: 3 },
      { word: 'mint', definition: 'a pale green color', example: 'The walls are painted mint green.', phonetic: '/mɪnt/', pos: 'adjective', difficulty: 2 },
      { word: 'peach', definition: 'a light orange-pink color', example: 'The sky turned peach at sunset.', phonetic: '/piːtʃ/', pos: 'adjective', difficulty: 2 },
      { word: 'burgundy', definition: 'a dark red-purple color', example: 'She chose a burgundy carpet.', phonetic: '/ˈbɜːrɡəndi/', pos: 'adjective', difficulty: 3 },
      { word: 'charcoal', definition: 'a very dark gray color', example: 'The charcoal suit looks elegant.', phonetic: '/ˈtʃɑːrkoʊl/', pos: 'adjective', difficulty: 3 },
      { word: 'khaki', definition: 'a light brown-green color', example: 'He wore khaki pants.', phonetic: '/ˈkɑːki/', pos: 'adjective', difficulty: 3 },
      { word: 'scarlet', definition: 'a bright red color', example: 'The cardinal bird is scarlet.', phonetic: '/ˈskɑːrlət/', pos: 'adjective', difficulty: 3 },
      { word: 'crimson', definition: 'a deep red color', example: 'The rose is deep crimson.', phonetic: '/ˈkrɪmzn/', pos: 'adjective', difficulty: 3 },
      { word: 'aqua', definition: 'a light blue-green color', example: 'She swam in the aqua water.', phonetic: '/ˈækwə/', pos: 'adjective', difficulty: 2 },
      { word: 'fuchsia', definition: 'a bright pink-purple color', example: 'The fuchsia flowers are very showy.', phonetic: '/ˈfjuːʃə/', pos: 'adjective', difficulty: 3 },
      { word: 'mustard', definition: 'a dull yellow color', example: 'He wore a mustard-yellow hat.', phonetic: '/ˈmʌstərd/', pos: 'adjective', difficulty: 3 },
      { word: 'plum', definition: 'a dark purple color', example: 'The curtains are plum-colored.', phonetic: '/plʌm/', pos: 'adjective', difficulty: 2 },
      { word: 'olive', definition: 'a dull green color', example: 'She painted the door olive green.', phonetic: '/ˈɒlɪv/', pos: 'adjective', difficulty: 2 },
      { word: 'tan', definition: 'a light brown color', example: 'His shoes are tan.', phonetic: '/tæn/', pos: 'adjective', difficulty: 2 },
      { word: 'cyan', definition: 'a bright blue-green color', example: 'The cyan water is very clear.', phonetic: '/ˈsaɪæn/', pos: 'adjective', difficulty: 3 },
      { word: 'magenta', definition: 'a bright purple-red color', example: 'The magenta flowers stand out.', phonetic: '/məˈdʒentə/', pos: 'adjective', difficulty: 3 },
      { word: 'sapphire', definition: 'a bright blue color like the gem', example: 'Her eyes are sapphire blue.', phonetic: '/ˈsæfaɪər/', pos: 'adjective', difficulty: 3 },
      { word: 'emerald', definition: 'a bright green color like the gem', example: 'The emerald grass is very soft.', phonetic: '/ˈemərəld/', pos: 'adjective', difficulty: 3 },
      { word: 'ruby', definition: 'a deep red color like the gem', example: 'She wore a ruby necklace.', phonetic: '/ˈruːbi/', pos: 'adjective', difficulty: 3 },
    ],
    collocations: [
      { phrase: 'bright colors', meaning: 'strong, vivid colors that are easy to see' },
      { phrase: 'dark colors', meaning: 'colors that have black mixed in' },
      { phrase: 'light colors', meaning: 'pale colors with white mixed in' },
      { phrase: 'colorful painting', meaning: 'a painting with many different colors' },
    ],
    quizQuestions: [
      { type: 'mcq', question: 'What color is the sky on a clear day?', options: ['Green', 'Blue', 'Red', 'Yellow'], answer: 1, points: 10 },
      { type: 'mcq', question: 'What color is grass?', options: ['Blue', 'Red', 'Green', 'Orange'], answer: 2, points: 10 },
      { type: 'fill', question: 'The color of snow and milk is ___.', answer: 'white', points: 15 },
      { type: 'mcq', question: 'Which color is a mix of red and yellow?', options: ['Purple', 'Green', 'Orange', 'Brown'], answer: 2, points: 10 },
      { type: 'fill', question: 'A ___ is many colors across the sky after rain.', answer: 'rainbow', points: 15 },
    ]
  },
  {
    id: 'numbers',
    name: 'Numbers 1-100',
    icon: '🔢',
    difficulty: 1,
    description: 'Learn numbers from one to one hundred',
    words: [
      { word: 'one', definition: 'the number 1', example: 'I have one apple.', phonetic: '/wʌn/', pos: 'number', difficulty: 1 },
      { word: 'two', definition: 'the number 2', example: 'She has two cats.', phonetic: '/tuː/', pos: 'number', difficulty: 1 },
      { word: 'three', definition: 'the number 3', example: 'There are three birds.', phonetic: '/θriː/', pos: 'number', difficulty: 1 },
      { word: 'four', definition: 'the number 4', example: 'A table has four legs.', phonetic: '/fɔːr/', pos: 'number', difficulty: 1 },
      { word: 'five', definition: 'the number 5', example: 'I have five fingers on my hand.', phonetic: '/faɪv/', pos: 'number', difficulty: 1 },
      { word: 'six', definition: 'the number 6', example: 'There are six eggs in the box.', phonetic: '/sɪks/', pos: 'number', difficulty: 1 },
      { word: 'seven', definition: 'the number 7', example: 'There are seven days in a week.', phonetic: '/ˈsevn/', pos: 'number', difficulty: 1 },
      { word: 'eight', definition: 'the number 8', example: 'An octopus has eight arms.', phonetic: '/eɪt/', pos: 'number', difficulty: 1 },
      { word: 'nine', definition: 'the number 9', example: 'A cat has nine lives.', phonetic: '/naɪn/', pos: 'number', difficulty: 1 },
      { word: 'ten', definition: 'the number 10', example: 'I have ten toes.', phonetic: '/ten/', pos: 'number', difficulty: 1 },
      { word: 'eleven', definition: 'the number 11', example: 'There are eleven players on a team.', phonetic: '/ɪˈlevn/', pos: 'number', difficulty: 2 },
      { word: 'twelve', definition: 'the number 12', example: 'There are twelve months in a year.', phonetic: '/twelv/', pos: 'number', difficulty: 2 },
      { word: 'thirteen', definition: 'the number 13', example: 'Thirteen is an unlucky number for some.', phonetic: '/ˌθɜːrˈtiːn/', pos: 'number', difficulty: 2 },
      { word: 'fourteen', definition: 'the number 14', example: 'She is fourteen years old.', phonetic: '/ˌfɔːrˈtiːn/', pos: 'number', difficulty: 2 },
      { word: 'fifteen', definition: 'the number 15', example: 'There are fifteen students.', phonetic: '/ˌfɪfˈtiːn/', pos: 'number', difficulty: 2 },
      { word: 'sixteen', definition: 'the number 16', example: 'Sweet sixteen is a special birthday.', phonetic: '/ˌsɪksˈtiːn/', pos: 'number', difficulty: 2 },
      { word: 'seventeen', definition: 'the number 17', example: 'Seventeen is my lucky number.', phonetic: '/ˌsevnˈtiːn/', pos: 'number', difficulty: 2 },
      { word: 'eighteen', definition: 'the number 18', example: 'You can vote at eighteen.', phonetic: '/ˌeɪˈtiːn/', pos: 'number', difficulty: 2 },
      { word: 'nineteen', definition: 'the number 19', example: 'Nineteen is one less than twenty.', phonetic: '/ˌnaɪnˈtiːn/', pos: 'number', difficulty: 2 },
      { word: 'twenty', definition: 'the number 20', example: 'There are twenty students in the class.', phonetic: '/ˈtwenti/', pos: 'number', difficulty: 1 },
      { word: 'thirty', definition: 'the number 30', example: 'There are thirty days in April.', phonetic: '/ˈθɜːrti/', pos: 'number', difficulty: 2 },
      { word: 'forty', definition: 'the number 40', example: 'Forty minutes is a long time.', phonetic: '/ˈfɔːrti/', pos: 'number', difficulty: 2 },
      { word: 'fifty', definition: 'the number 50', example: 'There are fifty states in the USA.', phonetic: '/ˈfɪfti/', pos: 'number', difficulty: 2 },
      { word: 'sixty', definition: 'the number 60', example: 'There are sixty minutes in an hour.', phonetic: '/ˈsɪksti/', pos: 'number', difficulty: 2 },
      { word: 'seventy', definition: 'the number 70', example: 'He is seventy years old.', phonetic: '/ˈsevnti/', pos: 'number', difficulty: 2 },
      { word: 'eighty', definition: 'the number 80', example: 'She lived to be eighty.', phonetic: '/ˈeɪti/', pos: 'number', difficulty: 2 },
      { word: 'ninety', definition: 'the number 90', example: 'There are ninety nine problems.', phonetic: '/ˈnaɪnti/', pos: 'number', difficulty: 2 },
      { word: 'hundred', definition: 'the number 100', example: 'There are one hundred cents in a dollar.', phonetic: '/ˈhʌndrəd/', pos: 'number', difficulty: 2 },
      { word: 'first', definition: 'number 1 in order', example: 'She came first in the race.', phonetic: '/fɜːrst/', pos: 'adjective', difficulty: 2 },
      { word: 'second', definition: 'number 2 in order', example: 'February is the second month.', phonetic: '/ˈsekənd/', pos: 'adjective', difficulty: 2 },
      { word: 'third', definition: 'number 3 in order', example: 'He won third place.', phonetic: '/θɜːrd/', pos: 'adjective', difficulty: 2 },
      { word: 'fourth', definition: 'number 4 in order', example: 'This is my fourth cup of coffee.', phonetic: '/fɔːrθ/', pos: 'adjective', difficulty: 2 },
      { word: 'fifth', definition: 'number 5 in order', example: 'She lives on the fifth floor.', phonetic: '/fɪfθ/', pos: 'adjective', difficulty: 2 },
      { word: 'sixth', definition: 'number 6 in order', example: 'He is in the sixth grade.', phonetic: '/sɪksθ/', pos: 'adjective', difficulty: 3 },
      { word: 'seventh', definition: 'number 7 in order', example: 'Sunday is the seventh day.', phonetic: '/ˈsevnθ/', pos: 'adjective', difficulty: 3 },
      { word: 'eighth', definition: 'number 8 in order', example: 'She sits in the eighth row.', phonetic: '/eɪtθ/', pos: 'adjective', difficulty: 3 },
      { word: 'ninth', definition: 'number 9 in order', example: 'He is in the ninth inning.', phonetic: '/naɪnθ/', pos: 'adjective', difficulty: 3 },
      { word: 'tenth', definition: 'number 10 in order', example: 'This is the tenth time today.', phonetic: '/tenθ/', pos: 'adjective', difficulty: 3 },
      { word: 'twice', definition: 'two times', example: 'I called you twice.', phonetic: '/twaɪs/', pos: 'adverb', difficulty: 2 },
      { word: 'pair', definition: 'two things that go together', example: 'I need a pair of shoes.', phonetic: '/peər/', pos: 'noun', difficulty: 2 },
      { word: 'dozen', definition: 'twelve of something', example: 'I bought a dozen eggs.', phonetic: '/ˈdʌzn/', pos: 'noun', difficulty: 2 },
      { word: 'zero', definition: 'the number 0, nothing', example: 'The score is zero to zero.', phonetic: '/ˈzɪroʊ/', pos: 'number', difficulty: 1 },
      { word: 'half', definition: 'one of two equal parts', example: 'I ate half of the pizza.', phonetic: '/hæf/', pos: 'noun', difficulty: 2 },
      { word: 'quarter', definition: 'one of four equal parts', example: 'A quarter of an hour is 15 minutes.', phonetic: '/ˈkwɔːrtər/', pos: 'noun', difficulty: 2 },
      { word: 'double', definition: 'two times the amount', example: 'I got double the usual amount.', phonetic: '/ˈdʌbl/', pos: 'adjective', difficulty: 3 },
      { word: 'triple', definition: 'three times the amount', example: 'She earned triple points today.', phonetic: '/ˈtrɪpl/', pos: 'adjective', difficulty: 3 },
      { word: 'single', definition: 'only one', example: 'I need a single ticket.', phonetic: '/ˈsɪŋɡl/', pos: 'adjective', difficulty: 2 },
      { word: 'decimal', definition: 'a number with a dot', example: 'The number 1.5 is a decimal.', phonetic: '/ˈdesɪml/', pos: 'noun', difficulty: 3 },
      { word: 'percent', definition: 'out of one hundred', example: 'I scored 100 percent on the test.', phonetic: '/pərˈsent/', pos: 'noun', difficulty: 3 },
      { word: 'total', definition: 'the final sum of numbers', example: 'The total is fifteen dollars.', phonetic: '/ˈtoʊtl/', pos: 'noun', difficulty: 2 },
    ],
    collocations: [
      { phrase: 'first place', meaning: 'the top position in a competition' },
      { phrase: 'half price', meaning: 'something that costs 50% less' },
      { phrase: 'a pair of', meaning: 'two matching items' },
      { phrase: 'double check', meaning: 'to check something again carefully' },
    ],
    quizQuestions: [
      { type: 'mcq', question: 'How many legs does a dog have?', options: ['Two', 'Four', 'Six', 'Eight'], answer: 1, points: 10 },
      { type: 'fill', question: 'There are ___ months in a year.', answer: 'twelve', points: 15 },
      { type: 'mcq', question: 'What number comes after nineteen?', options: ['Eighteen', 'Twenty', 'Twenty-one', 'Thirty'], answer: 1, points: 10 },
      { type: 'fill', question: 'The number 0 is called ___.', answer: 'zero', points: 15 },
      { type: 'mcq', question: 'How many minutes are in an hour?', options: ['30', '45', '60', '100'], answer: 2, points: 10 },
      { type: 'fill', question: 'There are ___ days in a week.', answer: 'seven', points: 15 },
    ]
  },
  {
    id: 'family',
    name: 'Family Members',
    icon: '👨‍👩‍👧‍👦',
    difficulty: 1,
    description: 'Learn words for people in a family',
    words: [
      { word: 'mother', definition: 'a female parent', example: 'My mother makes delicious cookies.', phonetic: '/ˈmʌðər/', pos: 'noun', difficulty: 1, synonyms: ['mom', 'mommy', 'mum'] },
      { word: 'father', definition: 'a male parent', example: 'My father reads me stories at bedtime.', phonetic: '/ˈfɑːðər/', pos: 'noun', difficulty: 1, synonyms: ['dad', 'daddy'] },
      { word: 'sister', definition: 'a female sibling', example: 'My sister shares her toys with me.', phonetic: '/ˈsɪstər/', pos: 'noun', difficulty: 1 },
      { word: 'brother', definition: 'a male sibling', example: 'My brother plays soccer with me.', phonetic: '/ˈbrʌðər/', pos: 'noun', difficulty: 1 },
      { word: 'baby', definition: 'a very young child', example: 'The baby is learning to walk.', phonetic: '/ˈbeɪbi/', pos: 'noun', difficulty: 1 },
      { word: 'grandmother', definition: 'the mother of your parent', example: 'My grandmother tells the best stories.', phonetic: '/ˈɡrænmʌðər/', pos: 'noun', difficulty: 1, synonyms: ['grandma', 'granny'] },
      { word: 'grandfather', definition: 'the father of your parent', example: 'My grandfather taught me to fish.', phonetic: '/ˈɡrænfɑːðər/', pos: 'noun', difficulty: 1, synonyms: ['grandpa'] },
      { word: 'aunt', definition: 'the sister of your parent', example: 'My aunt visits us every summer.', phonetic: '/ænt/', pos: 'noun', difficulty: 1 },
      { word: 'uncle', definition: 'the brother of your parent', example: 'My uncle tells funny jokes.', phonetic: '/ˈʌŋkl/', pos: 'noun', difficulty: 1 },
      { word: 'cousin', definition: 'the child of your aunt or uncle', example: 'I play video games with my cousin.', phonetic: '/ˈkʌzn/', pos: 'noun', difficulty: 1 },
      { word: 'daughter', definition: 'a female child of a parent', example: 'She is my eldest daughter.', phonetic: '/ˈdɔːtər/', pos: 'noun', difficulty: 2 },
      { word: 'son', definition: 'a male child of a parent', example: 'He is my youngest son.', phonetic: '/sʌn/', pos: 'noun', difficulty: 1 },
      { word: 'parent', definition: 'a mother or father of a child', example: 'My parents love me very much.', phonetic: '/ˈperənt/', pos: 'noun', difficulty: 1 },
      { word: 'child', definition: 'a young person, a son or daughter', example: 'Every child loves to play.', phonetic: '/tʃaɪld/', pos: 'noun', difficulty: 1 },
      { word: 'twin', definition: 'one of two children born together', example: 'My twin and I dress the same.', phonetic: '/twɪn/', pos: 'noun', difficulty: 2 },
      { word: 'family', definition: 'a group of related people', example: 'I love my family very much.', phonetic: '/ˈfæməli/', pos: 'noun', difficulty: 1 },
      { word: 'husband', definition: 'a man who is married', example: 'Her husband is a doctor.', phonetic: '/ˈhʌzbənd/', pos: 'noun', difficulty: 2 },
      { word: 'wife', definition: 'a woman who is married', example: 'His wife is a teacher.', phonetic: '/waɪf/', pos: 'noun', difficulty: 2 },
      { word: 'nephew', definition: 'the son of your brother or sister', example: 'My nephew is learning to ride a bike.', phonetic: '/ˈnefjuː/', pos: 'noun', difficulty: 2 },
      { word: 'niece', definition: 'the daughter of your brother or sister', example: 'My niece loves to play with dolls.', phonetic: '/niːs/', pos: 'noun', difficulty: 2 },
      { word: 'stepmother', definition: 'a woman married to your father', example: 'My stepmother is very kind.', phonetic: '/ˈstepmʌðər/', pos: 'noun', difficulty: 2 },
      { word: 'stepfather', definition: 'a man married to your mother', example: 'My stepfather helps me with homework.', phonetic: '/ˈstepfɑːðər/', pos: 'noun', difficulty: 2 },
      { word: 'stepsister', definition: 'the daughter of your stepparent', example: 'I share a room with my stepsister.', phonetic: '/ˈstepsɪstər/', pos: 'noun', difficulty: 2 },
      { word: 'stepbrother', definition: 'the son of your stepparent', example: 'My stepbrother and I play baseball.', phonetic: '/ˈstepbrʌðər/', pos: 'noun', difficulty: 2 },
      { word: 'grandparent', definition: 'a grandmother or grandfather', example: 'My grandparents live in Florida.', phonetic: '/ˈɡrænperənt/', pos: 'noun', difficulty: 2 },
      { word: 'grandson', definition: 'the son of your child', example: 'My grandson is five years old.', phonetic: '/ˈɡrænsʌn/', pos: 'noun', difficulty: 2 },
      { word: 'granddaughter', definition: 'the daughter of your child', example: 'My granddaughter sings beautifully.', phonetic: '/ˈɡrændɔːtər/', pos: 'noun', difficulty: 2 },
      { word: 'sibling', definition: 'a brother or sister', example: 'I have three siblings.', phonetic: '/ˈsɪblɪŋ/', pos: 'noun', difficulty: 2 },
      { word: 'relative', definition: 'a person in your family', example: 'All my relatives came to the party.', phonetic: '/ˈrelətɪv/', pos: 'noun', difficulty: 2 },
      { word: 'ancestor', definition: 'a family member from long ago', example: 'My ancestors came from Ireland.', phonetic: '/ˈænsestər/', pos: 'noun', difficulty: 3 },
      { word: 'descendant', definition: 'a family member from the future', example: 'We are descendants of the early settlers.', phonetic: '/dɪˈsendənt/', pos: 'noun', difficulty: 3 },
      { word: 'forever', definition: 'for all time, never ending', example: 'I will love you forever.', phonetic: '/fərˈevər/', pos: 'adverb', difficulty: 2 },
      { word: 'adopt', definition: 'to take a child into your family', example: 'They decided to adopt a baby.', phonetic: '/əˈdɒpt/', pos: 'verb', difficulty: 3 },
      { word: 'birth', definition: 'the moment a baby is born', example: 'The baby\'s birth was a happy day.', phonetic: '/bɜːrθ/', pos: 'noun', difficulty: 2 },
      { word: 'marriage', definition: 'the union of two people as husband and wife', example: 'Their marriage was beautiful.', phonetic: '/ˈmærɪdʒ/', pos: 'noun', difficulty: 2 },
      { word: 'divorce', definition: 'the legal end of a marriage', example: 'Divorce is hard for everyone.', phonetic: '/dɪˈvɔːrs/', pos: 'noun', difficulty: 3 },
      { word: 'widow', definition: 'a woman whose husband died', example: 'The widow lived alone in the house.', phonetic: '/ˈwɪdoʊ/', pos: 'noun', difficulty: 3 },
      { word: 'widower', definition: 'a man whose wife died', example: 'He became a widower last year.', phonetic: '/ˈwɪdoʊər/', pos: 'noun', difficulty: 3 },
      { word: 'only child', definition: 'a child with no siblings', example: 'As an only child, she gets all the attention.', phonetic: '/ˈoʊnli tʃaɪld/', pos: 'noun', difficulty: 2 },
      { word: 'middle child', definition: 'a child with both older and younger siblings', example: 'I am the middle child in my family.', phonetic: '/ˈmɪdl tʃaɪld/', pos: 'noun', difficulty: 2 },
      { word: 'youngest', definition: 'the child with the lowest age in the family', example: 'My youngest brother is two years old.', phonetic: '/ˈjʌŋɡɪst/', pos: 'adjective', difficulty: 2 },
      { word: 'eldest', definition: 'the child with the highest age in the family', example: 'My eldest sister is in college.', phonetic: '/ˈeldɪst/', pos: 'adjective', difficulty: 2 },
      { word: 'orphan', definition: 'a child whose parents have died', example: 'The orphan was adopted by a kind family.', phonetic: '/ˈɔːrfn/', pos: 'noun', difficulty: 3 },
      { word: 'guardian', definition: 'someone who takes care of a child', example: 'Her guardian picks her up from school.', phonetic: '/ˈɡɑːrdiən/', pos: 'noun', difficulty: 3 },
      { word: 'godparent', definition: 'a person who sponsors a child at baptism', example: 'My godmother gives me gifts on my birthday.', phonetic: '/ˈɡɒdperənt/', pos: 'noun', difficulty: 3 },
      { word: 'in-laws', definition: 'your spouse\'s family members', example: 'I get along with my in-laws.', phonetic: '/ˈɪn lɔːz/', pos: 'noun', difficulty: 3 },
      { word: 'half-brother', definition: 'a brother with one common parent', example: 'I have a half-brother from my father\'s side.', phonetic: '/ˈhæf brʌðər/', pos: 'noun', difficulty: 2 },
      { word: 'half-sister', definition: 'a sister with one common parent', example: 'My half-sister lives in another city.', phonetic: '/ˈhæf sɪstər/', pos: 'noun', difficulty: 2 },
      { word: 'fiancé', definition: 'a man engaged to be married', example: 'Her fiancé gave her a beautiful ring.', phonetic: '/fiˈɑːnseɪ/', pos: 'noun', difficulty: 3 },
      { word: 'fiancée', definition: 'a woman engaged to be married', example: 'His fiancée is planning the wedding.', phonetic: '/fiˈɑːnseɪ/', pos: 'noun', difficulty: 3 },
    ],
    collocations: [
      { phrase: 'family reunion', meaning: 'a gathering of family members' },
      { phrase: 'only child', meaning: 'a child with no brothers or sisters' },
      { phrase: 'close family', meaning: 'a family with strong bonds' },
      { phrase: 'immediate family', meaning: 'parents, siblings, and children' },
    ],
    quizQuestions: [
      { type: 'mcq', question: 'Who is the mother of your mother?', options: ['Aunt', 'Grandmother', 'Sister', 'Cousin'], answer: 1, points: 10 },
      { type: 'mcq', question: 'Your uncle\'s children are your ___?', options: ['Siblings', 'Cousins', 'Nephews', 'Nieces'], answer: 1, points: 10 },
      { type: 'fill', question: 'A male parent is called a ___.', answer: 'father', points: 15 },
      { type: 'fill', question: 'Your brother\'s son is your ___.', answer: 'nephew', points: 15 },
      { type: 'mcq', question: 'Who is a female sibling?', options: ['Brother', 'Sister', 'Uncle', 'Father'], answer: 1, points: 10 },
      { type: 'match', question: 'Match: Grandparent', pairs: [{ word: 'Grandparent', def: 'The parent of your parent' }, { word: 'Sibling', def: 'A brother or sister' }], points: 20 },
    ]
  },
  {
    id: 'food',
    name: 'Food & Drinks',
    icon: '🍽️',
    difficulty: 1,
    description: 'Learn words for food and drinks',
    words: [
      { word: 'apple', definition: 'a round red or green fruit', example: 'I eat an apple every day.', phonetic: '/ˈæpl/', pos: 'noun', difficulty: 1 },
      { word: 'banana', definition: 'a long yellow fruit', example: 'Monkeys love bananas.', phonetic: '/bəˈnænə/', pos: 'noun', difficulty: 1 },
      { word: 'bread', definition: 'a food made from flour and baked', example: 'I like to eat fresh bread with butter.', phonetic: '/bred/', pos: 'noun', difficulty: 1 },
      { word: 'milk', definition: 'a white drink from cows', example: 'I drink milk with my breakfast.', phonetic: '/mɪlk/', pos: 'noun', difficulty: 1 },
      { word: 'water', definition: 'a clear liquid you drink', example: 'I drink eight glasses of water a day.', phonetic: '/ˈwɔːtər/', pos: 'noun', difficulty: 1 },
      { word: 'rice', definition: 'a white grain eaten with meals', example: 'We eat rice with our dinner.', phonetic: '/raɪs/', pos: 'noun', difficulty: 1 },
      { word: 'egg', definition: 'an oval food from chickens', example: 'I eat a boiled egg for breakfast.', phonetic: '/eɡ/', pos: 'noun', difficulty: 1 },
      { word: 'meat', definition: 'the flesh of animals used as food', example: 'I like to eat meat with vegetables.', phonetic: '/miːt/', pos: 'noun', difficulty: 1 },
      { word: 'chicken', definition: 'a bird we eat for food', example: 'We have grilled chicken for dinner.', phonetic: '/ˈtʃɪkɪn/', pos: 'noun', difficulty: 1 },
      { word: 'fish', definition: 'a sea animal we eat', example: 'We eat fish on Fridays.', phonetic: '/fɪʃ/', pos: 'noun', difficulty: 1 },
      { word: 'cheese', definition: 'a yellow or white food made from milk', example: 'I put cheese on my sandwich.', phonetic: '/tʃiːz/', pos: 'noun', difficulty: 1 },
      { word: 'butter', definition: 'a yellow fat made from milk', example: 'Spread butter on the toast.', phonetic: '/ˈbʌtər/', pos: 'noun', difficulty: 1 },
      { word: 'soup', definition: 'a hot liquid food', example: 'I eat soup when I am sick.', phonetic: '/suːp/', pos: 'noun', difficulty: 1 },
      { word: 'salad', definition: 'a cold dish with vegetables', example: 'I like a salad with my meal.', phonetic: '/ˈsæləd/', pos: 'noun', difficulty: 1 },
      { word: 'pizza', definition: 'a flat bread with toppings', example: 'We order pizza on Friday nights.', phonetic: '/ˈpiːtsə/', pos: 'noun', difficulty: 1 },
      { word: 'pasta', definition: 'Italian food made from flour and water', example: 'I love pasta with tomato sauce.', phonetic: '/ˈpɑːstə/', pos: 'noun', difficulty: 1 },
      { word: 'sandwich', definition: 'two pieces of bread with filling', example: 'I packed a sandwich for lunch.', phonetic: '/ˈsænwɪtʃ/', pos: 'noun', difficulty: 1 },
      { word: 'juice', definition: 'a drink made from fruit', example: 'I drink orange juice for breakfast.', phonetic: '/dʒuːs/', pos: 'noun', difficulty: 1 },
      { word: 'coffee', definition: 'a hot dark drink that wakes you up', example: 'My dad drinks coffee in the morning.', phonetic: '/ˈkɒfi/', pos: 'noun', difficulty: 1 },
      { word: 'tea', definition: 'a hot drink made from leaves', example: 'I like tea with honey when I am sick.', phonetic: '/tiː/', pos: 'noun', difficulty: 1 },
      { word: 'cake', definition: 'a sweet baked dessert', example: 'I want cake for my birthday.', phonetic: '/keɪk/', pos: 'noun', difficulty: 1 },
      { word: 'cookie', definition: 'a small sweet baked treat', example: 'My mom makes chocolate chip cookies.', phonetic: '/ˈkʊki/', pos: 'noun', difficulty: 1 },
      { word: 'ice cream', definition: 'a cold sweet dessert', example: 'We eat ice cream on hot summer days.', phonetic: '/ˈaɪs kriːm/', pos: 'noun', difficulty: 1 },
      { word: 'chocolate', definition: 'a sweet brown food', example: 'I love chocolate for dessert.', phonetic: '/ˈtʃɒklət/', pos: 'noun', difficulty: 1 },
      { word: 'candy', definition: 'a sweet food made from sugar', example: 'I got candy for Halloween.', phonetic: '/ˈkændi/', pos: 'noun', difficulty: 1 },
      { word: 'fruit', definition: 'sweet food that grows on plants', example: 'I eat fruit every day for a snack.', phonetic: '/fruːt/', pos: 'noun', difficulty: 1 },
      { word: 'vegetable', definition: 'plant food that is good for you', example: 'Eat your vegetables to grow strong.', phonetic: '/ˈvedʒtəbl/', pos: 'noun', difficulty: 1 },
      { word: 'potato', definition: 'a brown root vegetable', example: 'I like baked potatoes with butter.', phonetic: '/pəˈteɪtoʊ/', pos: 'noun', difficulty: 1 },
      { word: 'tomato', definition: 'a red fruit used in cooking', example: 'I put tomato on my sandwich.', phonetic: '/təˈmɑːtoʊ/', pos: 'noun', difficulty: 1 },
      { word: 'onion', definition: 'a round layered vegetable', example: 'The onion makes me cry when I cut it.', phonetic: '/ˈʌnjən/', pos: 'noun', difficulty: 1 },
      { word: 'carrot', definition: 'a long orange root vegetable', example: 'Rabbits love to eat carrots.', phonetic: '/ˈkærət/', pos: 'noun', difficulty: 1 },
      { word: 'corn', definition: 'a yellow grain on a cob', example: 'We eat corn on the cob in summer.', phonetic: '/kɔːrn/', pos: 'noun', difficulty: 1 },
      { word: 'bread', definition: 'a food made from flour and baked', example: 'The fresh bread smells wonderful.', phonetic: '/bred/', pos: 'noun', difficulty: 1 },
      { word: 'pancake', definition: 'a flat round breakfast food', example: 'We have pancakes with syrup on Sunday.', phonetic: '/ˈpænkeɪk/', pos: 'noun', difficulty: 1 },
      { word: 'cereal', definition: 'a breakfast food with milk', example: 'I eat cereal every morning.', phonetic: '/ˈsɪriəl/', pos: 'noun', difficulty: 1 },
      { word: 'yogurt', definition: 'a thick sour milk food', example: 'I like strawberry yogurt.', phonetic: '/ˈjoʊɡərt/', pos: 'noun', difficulty: 1 },
      { word: 'honey', definition: 'a sweet food made by bees', example: 'I put honey in my tea.', phonetic: '/ˈhʌni/', pos: 'noun', difficulty: 1 },
      { word: 'jam', definition: 'a sweet spread made from fruit', example: 'I spread jam on my toast.', phonetic: '/dʒæm/', pos: 'noun', difficulty: 1 },
      { word: 'noodle', definition: 'a long thin strip of pasta', example: 'I eat noodles with soup.', phonetic: '/ˈnuːdl/', pos: 'noun', difficulty: 1 },
      { word: 'dumpling', definition: 'a piece of dough with filling', example: 'We eat dumplings on New Year.', phonetic: '/ˈdʌmplɪŋ/', pos: 'noun', difficulty: 2 },
      { word: 'steak', definition: 'a thick slice of meat for cooking', example: 'My dad grills steak on the barbecue.', phonetic: '/steɪk/', pos: 'noun', difficulty: 2 },
      { word: 'shrimp', definition: 'a small sea animal you can eat', example: 'I ate shrimp cocktail at the party.', phonetic: '/ʃrɪmp/', pos: 'noun', difficulty: 2 },
      { word: 'sausage', definition: 'a tube of seasoned meat', example: 'We eat sausage for breakfast.', phonetic: '/ˈsɔːsɪdʒ/', pos: 'noun', difficulty: 2 },
      { word: 'bacon', definition: 'thin strips of salty pork', example: 'The smell of bacon woke me up.', phonetic: '/ˈbeɪkən/', pos: 'noun', difficulty: 2 },
      { word: 'mushroom', definition: 'a fungus used in cooking', example: 'I put mushrooms on my pizza.', phonetic: '/ˈmʌʃruːm/', pos: 'noun', difficulty: 2 },
      { word: 'pepper', definition: 'a spice with a strong taste', example: 'I add pepper to my food.', phonetic: '/ˈpepər/', pos: 'noun', difficulty: 2 },
      { word: 'salt', definition: 'a white mineral used to flavor food', example: 'I put a little salt on my eggs.', phonetic: '/sɔːlt/', pos: 'noun', difficulty: 1 },
      { word: 'sugar', definition: 'a sweet white substance from plants', example: 'I put sugar in my coffee.', phonetic: '/ˈʃʊɡər/', pos: 'noun', difficulty: 1 },
      { word: 'vinegar', definition: 'a sour liquid used in cooking', example: 'I use vinegar for the salad dressing.', phonetic: '/ˈvɪnɪɡər/', pos: 'noun', difficulty: 2 },
      { word: 'oil', definition: 'a liquid fat used for cooking', example: 'I fry the egg in hot oil.', phonetic: '/ɔɪl/', pos: 'noun', difficulty: 2 },
    ],
    collocations: [
      { phrase: 'fast food', meaning: 'food that is prepared and served quickly' },
      { phrase: 'home cooking', meaning: 'food made at home, not in a restaurant' },
      { phrase: 'fresh fruit', meaning: 'fruit that is picked recently and not processed' },
      { phrase: 'junk food', meaning: 'food that is unhealthy but tastes good' },
    ],
    quizQuestions: [
      { type: 'mcq', question: 'Which is a fruit?', options: ['Carrot', 'Apple', 'Onion', 'Potato'], answer: 1, points: 10 },
      { type: 'mcq', question: 'What do bees make?', options: ['Butter', 'Jam', 'Honey', 'Sugar'], answer: 2, points: 10 },
      { type: 'fill', question: 'A long yellow fruit is a ___.', answer: 'banana', points: 15 },
      { type: 'mcq', question: 'Which is a drink?', options: ['Bread', 'Pizza', 'Juice', 'Cake'], answer: 2, points: 10 },
      { type: 'match', question: 'Match: Ice cream', pairs: [{ word: 'Ice cream', def: 'Cold sweet dessert' }, { word: 'Soup', def: 'Hot liquid food' }], points: 20 },
      { type: 'fill', question: 'I put ___ on my toast for a sweet taste.', answer: 'jam', points: 15 },
    ]
  },
];

const ADDITIONAL_CATEGORIES = [
  { id: 'body-parts', name: 'Body Parts', icon: '🧍', difficulty: 1, description: 'Learn the names of body parts' },
  { id: 'clothing', name: 'Clothing', icon: '👕', difficulty: 1, description: 'Learn words for clothes and accessories' },
  { id: 'weather', name: 'Weather', icon: '🌤️', difficulty: 1, description: 'Learn about weather and seasons' },
  { id: 'school', name: 'School Supplies', icon: '✏️', difficulty: 1, description: 'Learn words for school items' },
  { id: 'seasons', name: 'Seasons', icon: '🌺', difficulty: 1, description: 'Learn about the four seasons' },
  { id: 'days', name: 'Days of the Week', icon: '📅', difficulty: 1, description: 'Learn the seven days of the week' },
  { id: 'months', name: 'Months', icon: '🗓️', difficulty: 1, description: 'Learn the twelve months' },
  { id: 'shapes', name: 'Shapes', icon: '🔴', difficulty: 1, description: 'Learn names of different shapes' },
  { id: 'professions', name: 'Professions', icon: '👔', difficulty: 2, description: 'Learn job titles and occupations' },
  { id: 'transport', name: 'Transportation', icon: '🚗', difficulty: 2, description: 'Learn about vehicles and transport' },
  { id: 'places-town', name: 'Places in Town', icon: '🏛️', difficulty: 2, description: 'Learn about places in a town' },
  { id: 'house-rooms', name: 'House Rooms', icon: '🏠', difficulty: 2, description: 'Learn about rooms in a house' },
  { id: 'furniture', name: 'Furniture', icon: '🪑', difficulty: 2, description: 'Learn about furniture and home items' },
  { id: 'kitchen', name: 'Kitchen Items', icon: '🍳', difficulty: 2, description: 'Learn about kitchen tools and items' },
  { id: 'bathroom', name: 'Bathroom Items', icon: '🚿', difficulty: 2, description: 'Learn about bathroom items' },
  { id: 'toys', name: 'Toys & Games', icon: '🧸', difficulty: 2, description: 'Learn toy and game names' },
  { id: 'sports', name: 'Sports', icon: '⚽', difficulty: 2, description: 'Learn names of sports' },
  { id: 'instruments', name: 'Musical Instruments', icon: '🎵', difficulty: 2, description: 'Learn about musical instruments' },
  { id: 'emotions', name: 'Emotions', icon: '😊', difficulty: 2, description: 'Learn words for feelings' },
  { id: 'personality', name: 'Personality', icon: '🧠', difficulty: 2, description: 'Learn words to describe personality' },
  { id: 'actions', name: 'Actions (Verbs)', icon: '🏃', difficulty: 2, description: 'Learn action words' },
  { id: 'adjectives', name: 'Adjectives', icon: '📝', difficulty: 2, description: 'Learn describing words' },
  { id: 'prepositions', name: 'Prepositions', icon: '📍', difficulty: 2, description: 'Learn position words' },
  { id: 'conjunctions', name: 'Conjunctions', icon: '🔗', difficulty: 2, description: 'Learn joining words' },
  { id: 'question-words', name: 'Question Words', icon: '❓', difficulty: 2, description: 'Learn how to ask questions' },
  { id: 'greetings', name: 'Greetings', icon: '👋', difficulty: 1, description: 'Learn greetings and farewells' },
  { id: 'polite', name: 'Polite Expressions', icon: '🙏', difficulty: 1, description: 'Learn polite words and phrases' },
  { id: 'opposites', name: 'Opposites (Antonyms)', icon: '⬆️⬇️', difficulty: 2, description: 'Learn opposite words' },
  { id: 'synonyms', name: 'Synonyms', icon: '📖', difficulty: 2, description: 'Learn words with similar meanings' },
  { id: 'phrasal-common', name: 'Phrasal Verbs (Common)', icon: '🔑', difficulty: 3, description: 'Learn common phrasal verbs' },
  { id: 'phrasal-movement', name: 'Phrasal Verbs (Movement)', icon: '🚶', difficulty: 3, description: 'Learn movement phrasal verbs' },
  { id: 'phrasal-communication', name: 'Phrasal Verbs (Communication)', icon: '💬', difficulty: 3, description: 'Learn communication phrasal verbs' },
  { id: 'collocations-food', name: 'Collocations (Food)', icon: '🍕', difficulty: 3, description: 'Learn food word combinations' },
  { id: 'collocations-clothing', name: 'Collocations (Clothing)', icon: '👗', difficulty: 3, description: 'Learn clothing word combinations' },
  { id: 'collocations-weather', name: 'Collocations (Weather)', icon: '🌧️', difficulty: 3, description: 'Learn weather word combinations' },
  { id: 'collocations-emotions', name: 'Collocations (Emotions)', icon: '💖', difficulty: 3, description: 'Learn emotion word combinations' },
  { id: 'idioms-common', name: 'Idioms (Common)', icon: '💡', difficulty: 3, description: 'Learn common English idioms' },
  { id: 'idioms-animal', name: 'Idioms (Animal)', icon: '🐘', difficulty: 3, description: 'Learn animal-based idioms' },
  { id: 'nature', name: 'Nature & Environment', icon: '🌿', difficulty: 2, description: 'Learn nature vocabulary' },
  { id: 'space', name: 'Space & Astronomy', icon: '🌌', difficulty: 2, description: 'Learn about space and stars' },
  { id: 'technology', name: 'Technology', icon: '💻', difficulty: 2, description: 'Learn technology words' },
  { id: 'health', name: 'Health & Body', icon: '🏥', difficulty: 2, description: 'Learn health vocabulary' },
  { id: 'hobbies', name: 'Hobbies', icon: '🎨', difficulty: 2, description: 'Learn hobby names' },
  { id: 'travel', name: 'Travel & Tourism', icon: '✈️', difficulty: 3, description: 'Learn travel vocabulary' },
  { id: 'shopping', name: 'Shopping', icon: '🛍️', difficulty: 3, description: 'Learn shopping vocabulary' },
  { id: 'restaurant', name: 'Restaurant', icon: '🍴', difficulty: 3, description: 'Learn restaurant vocabulary' },
  { id: 'emergency', name: 'Emergency & Safety', icon: '🚨', difficulty: 3, description: 'Learn safety vocabulary' },
  { id: 'fruits', name: 'Fruits', icon: '🍎', difficulty: 1, description: 'Learn fruit names' },
  { id: 'vegetables', name: 'Vegetables', icon: '🥕', difficulty: 1, description: 'Learn vegetable names' },
  { id: 'classroom', name: 'Classroom Objects', icon: '📚', difficulty: 1, description: 'Learn classroom item names' },
  { id: 'nature-places', name: 'Natural Places', icon: '🏔️', difficulty: 2, description: 'Learn natural landscape words' },
  { id: 'time', name: 'Time Expressions', icon: '⏰', difficulty: 2, description: 'Learn how to tell and talk about time' },
  { id: 'holidays', name: 'Holidays & Celebrations', icon: '🎉', difficulty: 2, description: 'Learn holiday and celebration words' },
  { id: 'animals-birds', name: 'Birds', icon: '🦅', difficulty: 2, description: 'Learn bird names and types' },
];

const PLACEHOLDER_WORDS = [
  { word: 'example', definition: 'a sample to show how something works', example: 'This is an example of a word.', phonetic: '/ɪɡˈzæmpl/', pos: 'noun', difficulty: 1 },
  { word: 'practice', definition: 'to do something again to get better', example: 'Practice makes perfect.', phonetic: '/ˈpræktɪs/', pos: 'verb', difficulty: 1 },
  { word: 'learn', definition: 'to get new knowledge or skill', example: 'I learn new words every day.', phonetic: '/lɜːrn/', pos: 'verb', difficulty: 1 },
  { word: 'study', definition: 'to spend time learning', example: 'I study English at school.', phonetic: '/ˈstʌdi/', pos: 'verb', difficulty: 1 },
  { word: 'remember', definition: 'to keep in your mind', example: 'Try to remember the new words.', phonetic: '/rɪˈmembər/', pos: 'verb', difficulty: 2 },
  { word: 'understand', definition: 'to know the meaning of something', example: 'I understand the lesson now.', phonetic: '/ˌʌndərˈstænd/', pos: 'verb', difficulty: 2 },
  { word: 'speak', definition: 'to talk, to say words', example: 'I can speak English.', phonetic: '/spiːk/', pos: 'verb', difficulty: 1 },
  { word: 'listen', definition: 'to pay attention to sound', example: 'Listen to the teacher.', phonetic: '/ˈlɪsn/', pos: 'verb', difficulty: 1 },
  { word: 'write', definition: 'to make letters or words on paper', example: 'Write your name on the paper.', phonetic: '/raɪt/', pos: 'verb', difficulty: 1 },
  { word: 'read', definition: 'to look at words and understand them', example: 'I read a book every night.', phonetic: '/riːd/', pos: 'verb', difficulty: 1 },
];

const collocationsPlaceholder = [
  { phrase: 'hard work', meaning: 'work that requires a lot of effort' },
  { phrase: 'good luck', meaning: 'wishing someone success' },
  { phrase: 'make progress', meaning: 'to improve or move forward' },
  { phrase: 'take a break', meaning: 'to rest for a short time' },
];

const quizPlaceholder = [
  { type: 'mcq', question: 'Which word means to get new knowledge?', options: ['Forget', 'Learn', 'Sleep', 'Run'], answer: 1, points: 10 },
  { type: 'fill', question: 'To ___ is to look at words and understand them.', answer: 'read', points: 15 },
  { type: 'mcq', question: 'What should you do to get better at something?', options: ['Stop', 'Practice', 'Sleep', 'Forget'], answer: 1, points: 10 },
];
