const CATEGORY_WORDS = {
  'body-parts': [
    ['head', 'the top part of your body with your face', 'I wear a hat on my head.', '/hed/', 'noun', 1],
    ['hair', 'the thin strands that grow on your head', 'She has long brown hair.', '/heər/', 'noun', 1],
    ['face', 'the front part of your head', 'She has a smile on her face.', '/feɪs/', 'noun', 1],
    ['eye', 'the part of your body you see with', 'I have blue eyes.', '/aɪ/', 'noun', 1],
    ['ear', 'the part of your body you hear with', 'The rabbit has long ears.', '/ɪər/', 'noun', 1],
    ['nose', 'the part of your face you smell with', 'My nose is cold in winter.', '/noʊz/', 'noun', 1],
    ['mouth', 'the part of your face you eat and speak with', 'Open your mouth for the dentist.', '/maʊθ/', 'noun', 1],
    ['tooth', 'the hard white things in your mouth', 'I brush my tooth every morning.', '/tuːθ/', 'noun', 1],
    ['tongue', 'the soft part inside your mouth you taste with', 'The hot soup burned my tongue.', '/tʌŋ/', 'noun', 2],
    ['lip', 'the soft edges around your mouth', 'She put lipstick on her lips.', '/lɪp/', 'noun', 2],
    ['neck', 'the part connecting your head to your body', 'I wear a scarf around my neck.', '/nek/', 'noun', 1],
    ['shoulder', 'the joint between your arm and body', 'I carry my bag on my shoulder.', '/ˈʃoʊldər/', 'noun', 1],
    ['arm', 'the part from your shoulder to your hand', 'I broke my arm last year.', '/ɑːrm/', 'noun', 1],
    ['elbow', 'the joint in the middle of your arm', 'I hit my elbow on the table.', '/ˈelboʊ/', 'noun', 2],
    ['wrist', 'the joint between your arm and hand', 'I wear a watch on my wrist.', '/rɪst/', 'noun', 2],
    ['hand', 'the part at the end of your arm with fingers', 'I write with my right hand.', '/hænd/', 'noun', 1],
    ['finger', 'one of the five parts at the end of your hand', 'I have five fingers on each hand.', '/ˈfɪŋɡər/', 'noun', 1],
    ['thumb', 'the short thick finger on your hand', 'I use my thumb to press buttons.', '/θʌm/', 'noun', 2],
    ['nail', 'the hard layer at the tip of your finger', 'I cut my nails every week.', '/neɪl/', 'noun', 2],
    ['chest', 'the front part of your body between neck and stomach', 'The doctor listened to my chest.', '/tʃest/', 'noun', 2],
    ['back', 'the rear part of your body', 'I carry my sister on my back.', '/bæk/', 'noun', 1],
    ['stomach', 'the front part of your body below your chest', 'My stomach hurts after eating.', '/ˈstʌmək/', 'noun', 2],
    ['leg', 'the part from your hip to your foot', 'I kicked the ball with my leg.', '/leɡ/', 'noun', 1],
    ['knee', 'the joint in the middle of your leg', 'I hurt my knee when I fell.', '/niː/', 'noun', 2],
    ['ankle', 'the joint between your leg and foot', 'I twisted my ankle running.', '/ˈæŋkl/', 'noun', 2],
    ['foot', 'the part at the end of your leg you stand on', 'I have two feet.', '/fʊt/', 'noun', 1],
    ['toe', 'one of the five parts at the end of your foot', 'I stubbed my toe on the door.', '/toʊ/', 'noun', 2],
    ['heel', 'the back part of your foot', 'The heel of my shoe is worn.', '/hiːl/', 'noun', 2],
    ['chin', 'the bottom part of your face below your mouth', 'He has a beard on his chin.', '/tʃɪn/', 'noun', 2],
    ['cheek', 'the side of your face below your eye', 'Her cheeks are pink from the cold.', '/tʃiːk/', 'noun', 2],
    ['forehead', 'the part of your face above your eyes', 'He wiped sweat from his forehead.', '/ˈfɔːrhed/', 'noun', 2],
    ['eyebrow', 'the line of hair above your eye', 'She raised her eyebrows in surprise.', '/ˈaɪbraʊ/', 'noun', 2],
    ['eyelash', 'the short hairs on the edge of your eyelid', 'She has long eyelashes.', '/ˈaɪlæʃ/', 'noun', 2],
    ['skin', 'the outer covering of your body', 'Human skin is sensitive to sun.', '/skɪn/', 'noun', 1],
    ['bone', 'the hard parts inside your body', 'The X-ray showed a broken bone.', '/boʊn/', 'noun', 2],
    ['muscle', 'the parts of your body that help you move', 'Exercise makes your muscles stronger.', '/ˈmʌsl/', 'noun', 2],
    ['heart', 'the organ that pumps blood in your body', 'My heart beats fast when I run.', '/hɑːrt/', 'noun', 1],
    ['lung', 'the organ you breathe with', 'Your lungs fill with air when you breathe.', '/lʌŋ/', 'noun', 2],
    ['brain', 'the organ inside your head you think with', 'The brain controls your whole body.', '/breɪn/', 'noun', 2],
    ['blood', 'the red liquid in your body', 'Blood flows through your veins.', '/blʌd/', 'noun', 1],
    ['rib', 'the bones that protect your chest', 'I broke a rib in the accident.', '/rɪb/', 'noun', 2],
    ['spine', 'the line of bones down your back', 'The spine helps you stand straight.', '/spaɪn/', 'noun', 2],
    ['hip', 'the joint between your leg and body', 'I put my hands on my hips.', '/hɪp/', 'noun', 2],
    ['thumb', 'the short thick finger on your hand', 'I hit my thumb with the hammer.', '/θʌm/', 'noun', 2],
    ['waist', 'the narrow part of your body between ribs and hips', 'She wears a belt around her waist.', '/weɪst/', 'noun', 2],
    ['thumb', 'the short thick finger', 'I gave a thumbs up.', '/θʌm/', 'noun', 2],
    ['palm', 'the inside part of your hand', 'I read his palm for fun.', '/pɑːm/', 'noun', 2],
    ['fist', 'a hand with fingers closed tight', 'He made a fist and knocked.', '/fɪst/', 'noun', 2],
    ['jaw', 'the bottom part of your mouth that moves', 'My jaw dropped in surprise.', '/dʒɔː/', 'noun', 2],
    ['wrinkle', 'a small line on your skin from age', 'My grandmother has wrinkles on her face.', '/ˈrɪŋkl/', 'noun', 3],
  ],
  'clothing': [
    ['shirt', 'clothing for the upper body with sleeves and a collar', 'I wear a blue shirt to school.', '/ʃɜːrt/', 'noun', 1],
    ['pants', 'clothing for your legs from waist to ankle', 'He wears black pants.', '/pænts/', 'noun', 1],
    ['dress', 'a one-piece clothing for women or girls', 'She wore a pink dress to the party.', '/dres/', 'noun', 1],
    ['skirt', 'clothing for the lower body worn by women', 'She wears a skirt in summer.', '/skɜːrt/', 'noun', 1],
    ['shorts', 'short pants that come above the knee', 'I wear shorts when it is hot.', '/ʃɔːrts/', 'noun', 1],
    ['jacket', 'a short coat for cool weather', 'I put on my jacket before going out.', '/ˈdʒækɪt/', 'noun', 1],
    ['coat', 'a warm piece of clothing worn over other clothes', 'I wear a heavy coat in winter.', '/koʊt/', 'noun', 1],
    ['hat', 'a covering for the head', 'I wear a hat to block the sun.', '/hæt/', 'noun', 1],
    ['cap', 'a soft hat with a visor', 'He wears a baseball cap.', '/kæp/', 'noun', 1],
    ['scarf', 'a piece of cloth worn around the neck', 'I wear a scarf when it is cold.', '/skɑːrf/', 'noun', 1],
    ['gloves', 'coverings for your hands', 'I wear gloves in the snow.', '/ɡlʌvz/', 'noun', 1],
    ['shoes', 'coverings for your feet', 'I tie my shoes before running.', '/ʃuːz/', 'noun', 1],
    ['socks', 'soft coverings for your feet inside shoes', 'I wear warm socks in winter.', '/sɒks/', 'noun', 1],
    ['boots', 'tall shoes that cover your ankle', 'I wear boots when it rains.', '/buːts/', 'noun', 1],
    ['sneakers', 'comfortable shoes for sports and running', 'I wear sneakers for gym class.', '/ˈsniːkərz/', 'noun', 2],
    ['sandals', 'open shoes worn in warm weather', 'I wear sandals at the beach.', '/ˈsændlz/', 'noun', 2],
    ['belt', 'a band worn around the waist to hold pants up', 'I need a belt for these pants.', '/belt/', 'noun', 1],
    ['tie', 'a long piece of cloth worn around the neck', 'My father wears a tie to work.', '/taɪ/', 'noun', 1],
    ['suit', 'a matching jacket and pants worn for formal events', 'He wore a suit to the wedding.', '/suːt/', 'noun', 2],
    ['sweater', 'a warm top made of knitted wool or cotton', 'I wear a sweater when it is chilly.', '/ˈswetər/', 'noun', 1],
    ['jeans', 'casual pants made of denim', 'I wear jeans on the weekend.', '/dʒiːnz/', 'noun', 1],
    ['shorts', 'pants that end above the knee', 'I wear shorts in summer.', '/ʃɔːrts/', 'noun', 1],
    ['vest', 'a piece of clothing without sleeves worn over a shirt', 'He wore a vest over his shirt.', '/vest/', 'noun', 2],
    ['uniform', 'special clothes worn by a group like students or police', 'We wear a uniform to school.', '/ˈjuːnɪfɔːrm/', 'noun', 1],
    ['pajamas', 'soft clothes worn for sleeping', 'I wear pajamas to bed.', '/pəˈdʒɑːməz/', 'noun', 1],
    ['slippers', 'soft shoes worn indoors', 'I wear slippers around the house.', '/ˈslɪpərz/', 'noun', 2],
    ['umbrella', 'a tool used to keep rain off you', 'I take my umbrella when it rains.', '/ʌmˈbrelə/', 'noun', 2],
    ['watch', 'a small clock worn on your wrist', 'I check my watch for the time.', '/wɒtʃ/', 'noun', 1],
    ['ring', 'a small circle of metal worn on a finger', 'She wears a gold ring.', '/rɪŋ/', 'noun', 2],
    ['necklace', 'a piece of jewelry worn around the neck', 'She wore a pretty necklace.', '/ˈneklɪs/', 'noun', 2],
    ['bracelet', 'a piece of jewelry worn around the wrist', 'She has a silver bracelet.', '/ˈbreɪslɪt/', 'noun', 2],
    ['earring', 'a piece of jewelry worn on the ear', 'She wears gold earrings.', '/ˈɪrɪŋ/', 'noun', 2],
    ['pocket', 'a small bag sewn into clothing', 'I keep my phone in my pocket.', '/ˈpɒkɪt/', 'noun', 1],
    ['button', 'a small round fastener for clothing', 'I button my shirt.', '/ˈbʌtn/', 'noun', 1],
    ['zipper', 'a device used to fasten clothing', 'Zip up your jacket.', '/ˈzɪpər/', 'noun', 2],
    ['hood', 'a covering for the head attached to a jacket', 'My jacket has a hood.', '/hʊd/', 'noun', 2],
    ['sleeve', 'the part of a shirt that covers your arm', 'I rolled up my sleeves.', '/sliːv/', 'noun', 2],
    ['collar', 'the part of a shirt that goes around your neck', 'I straightened my collar.', '/ˈkɒlər/', 'noun', 2],
    ['strap', 'a narrow piece of leather or fabric used to carry something', 'My bag has a long strap.', '/stræp/', 'noun', 2],
    ['lace', 'a thin string used to tie shoes', 'I tied my shoe laces.', '/leɪs/', 'noun', 2],
    ['fabric', 'cloth material used to make clothes', 'This shirt is made of soft fabric.', '/ˈfæbrɪk/', 'noun', 2],
    ['cotton', 'a soft natural fabric from cotton plants', 'My shirt is made of cotton.', '/ˈkɒtn/', 'noun', 2],
    ['wool', 'a warm fabric from sheep', 'This sweater is made of wool.', '/wʊl/', 'noun', 2],
    ['leather', 'a strong material made from animal skin', 'My shoes are made of leather.', '/ˈleðər/', 'noun', 2],
    ['size', 'how big or small a piece of clothing is', 'I wear size small shirts.', '/saɪz/', 'noun', 1],
    ['try on', 'to put on clothing to see if it fits', 'I want to try on this dress.', '/traɪ ɒn/', 'verb', 2],
    ['wear', 'to have clothing on your body', 'I wear a uniform to school.', '/weər/', 'verb', 1],
    ['fold', 'to bend cloth to make it smaller and neater', 'I fold my clothes after washing.', '/foʊld/', 'verb', 2],
    ['iron', 'to use a hot tool to remove wrinkles from clothes', 'I iron my shirt for the party.', '/ˈaɪərn/', 'verb', 2],
    ['sew', 'to use a needle and thread to fix clothes', 'My grandmother taught me to sew.', '/soʊ/', 'verb', 3],
  ],
  'weather': [
    ['sunny', 'when the sun is shining and there are no clouds', 'It is a sunny day today.', '/ˈsʌni/', 'adjective', 1],
    ['rainy', 'when rain is falling from the sky', 'I carry an umbrella on rainy days.', '/ˈreɪni/', 'adjective', 1],
    ['cloudy', 'when the sky is full of clouds', 'It is cloudy today; it might rain.', '/ˈklaʊdi/', 'adjective', 1],
    ['windy', 'when there is a lot of wind', 'It is too windy to fly a kite.', '/ˈwɪndi/', 'adjective', 1],
    ['snowy', 'when snow is falling from the sky', 'We stay inside on snowy days.', '/ˈsnoʊi/', 'adjective', 1],
    ['stormy', 'when there is a storm with wind and rain', 'The stormy weather knocked down trees.', '/ˈstɔːrmi/', 'adjective', 2],
    ['foggy', 'when there is fog making it hard to see', 'Drive carefully on foggy mornings.', '/ˈfɒɡi/', 'adjective', 2],
    ['hot', 'when the temperature is very high', 'It is very hot in summer.', '/hɒt/', 'adjective', 1],
    ['cold', 'when the temperature is very low', 'I wear a coat on cold days.', '/koʊld/', 'adjective', 1],
    ['warm', 'pleasantly high temperature, not hot', 'It is warm and sunny today.', '/wɔːrm/', 'adjective', 1],
    ['cool', 'pleasantly low temperature, not cold', 'The evening is cool and pleasant.', '/kuːl/', 'adjective', 1],
    ['rain', 'water falling from clouds in the sky', 'The rain is falling heavily.', '/reɪn/', 'noun', 1],
    ['snow', 'white frozen water falling from the sky', 'The snow covers the ground.', '/snoʊ/', 'noun', 1],
    ['wind', 'moving air outside', 'The wind blows the leaves around.', '/wɪnd/', 'noun', 1],
    ['cloud', 'a white or gray shape in the sky', 'A big cloud covers the sun.', '/klaʊd/', 'noun', 1],
    ['fog', 'thick cloud near the ground that makes it hard to see', 'The fog is very thick this morning.', '/fɒɡ/', 'noun', 2],
    ['storm', 'bad weather with strong winds and rain', 'The storm lasted all night.', '/stɔːrm/', 'noun', 2],
    ['thunder', 'a loud sound during a storm', 'The thunder is very loud.', '/ˈθʌndər/', 'noun', 2],
    ['lightning', 'a bright flash of light during a storm', 'The lightning lit up the sky.', '/ˈlaɪtnɪŋ/', 'noun', 2],
    ['flood', 'when water covers land that is usually dry', 'The flood damaged many houses.', '/flʌd/', 'noun', 3],
    ['drought', 'a long period with no rain', 'The drought killed the crops.', '/draʊt/', 'noun', 3],
    ['temperature', 'how hot or cold the air is', 'The temperature today is 25 degrees.', '/ˈtemprətʃər/', 'noun', 2],
    ['degree', 'a unit for measuring temperature', 'It is 30 degrees Celsius.', '/dɪˈɡriː/', 'noun', 2],
    ['forecast', 'a prediction of what the weather will be', 'The forecast says it will rain tomorrow.', '/ˈfɔːrkæst/', 'noun', 2],
    ['season', 'one of the four parts of the year', 'My favorite season is summer.', '/ˈsiːzn/', 'noun', 1],
    ['spring', 'the season between winter and summer', 'Flowers bloom in spring.', '/sprɪŋ/', 'noun', 1],
    ['summer', 'the warmest season of the year', 'I go swimming in summer.', '/ˈsʌmər/', 'noun', 1],
    ['autumn', 'the season between summer and winter', 'Leaves fall in autumn.', '/ˈɔːtəm/', 'noun', 1],
    ['winter', 'the coldest season of the year', 'It snows in winter.', '/ˈwɪntər/', 'noun', 1],
    ['humid', 'when the air feels wet and sticky', 'It is very humid in the summer.', '/ˈhjuːmɪd/', 'adjective', 2],
    ['breeze', 'a gentle wind', 'A cool breeze feels nice on a hot day.', '/briːz/', 'noun', 2],
    ['icicle', 'a long stick of ice that hangs down', 'Icicles hang from the roof in winter.', '/ˈaɪsɪkl/', 'noun', 3],
    ['hail', 'small balls of ice that fall from the sky', 'The hail damaged the car.', '/heɪl/', 'noun', 3],
    ['dew', 'small drops of water on grass in the morning', 'The grass is wet with dew.', '/duː/', 'noun', 3],
    ['frost', 'a thin layer of ice on surfaces', 'The car windows have frost on them.', '/frɒst/', 'noun', 2],
    ['thermometer', 'a tool that measures temperature', 'The thermometer says 35 degrees.', '/θərˈmɒmɪtər/', 'noun', 3],
    ['rainbow', 'a curve of colors in the sky after rain', 'We saw a rainbow after the storm.', '/ˈreɪnboʊ/', 'noun', 1],
    ['puddle', 'a small pool of water on the ground after rain', 'Children jump in puddles.', '/ˈpʌdl/', 'noun', 2],
    ['umbrella', 'a tool that keeps you dry in the rain', 'Do not forget your umbrella.', '/ʌmˈbrelə/', 'noun', 1],
    ['raindrop', 'a single drop of rain', 'A raindrop landed on my nose.', '/ˈreɪndrɒp/', 'noun', 2],
    ['snowflake', 'a single piece of snow with a unique shape', 'No two snowflakes are alike.', '/ˈsnoʊfleɪk/', 'noun', 2],
    ['heatwave', 'a period of very hot weather', 'The heatwave lasted two weeks.', '/ˈhiːtweɪv/', 'noun', 3],
    ['freezing', 'very cold, below 0 degrees', 'It is freezing outside today.', '/ˈfriːzɪŋ/', 'adjective', 2],
    ['mild', 'not too hot and not too cold', 'The weather is mild today.', '/maɪld/', 'adjective', 2],
    ['clear', 'without clouds', 'The sky is clear and blue.', '/klɪər/', 'adjective', 1],
  ],
  'school': [
    ['pencil', 'a tool used for writing or drawing', 'I write with a pencil.', '/ˈpensl/', 'noun', 1],
    ['pen', 'a tool with ink used for writing', 'Please use a blue pen.', '/pen/', 'noun', 1],
    ['eraser', 'a tool used to remove pencil marks', 'I use an eraser to fix mistakes.', '/ɪˈreɪsər/', 'noun', 1],
    ['ruler', 'a straight tool used for measuring and drawing lines', 'Use a ruler to draw a straight line.', '/ˈruːlər/', 'noun', 1],
    ['book', 'a set of pages with words for reading', 'I read a book every night.', '/bʊk/', 'noun', 1],
    ['notebook', 'a book of blank pages for writing notes', 'I write in my notebook in class.', '/ˈnoʊtbʊk/', 'noun', 1],
    ['backpack', 'a bag you wear on your back to carry things', 'I carry my books in my backpack.', '/ˈbækpæk/', 'noun', 1],
    ['desk', 'a table used for studying or working', 'I sit at my desk to do homework.', '/desk/', 'noun', 1],
    ['chair', 'a seat with four legs and a back', 'Please sit on your chair.', '/tʃeər/', 'noun', 1],
    ['teacher', 'a person who teaches at school', 'My teacher helps me learn.', '/ˈtiːtʃər/', 'noun', 1],
    ['student', 'a person who studies at school', 'I am a student in grade four.', '/ˈstuːdnt/', 'noun', 1],
    ['classroom', 'a room where lessons happen at school', 'Our classroom has a whiteboard.', '/ˈklæsruːm/', 'noun', 1],
    ['homework', 'schoolwork done at home', 'I do my homework after dinner.', '/ˈhoʊmwɜːrk/', 'noun', 1],
    ['test', 'a set of questions to check what you know', 'We have a math test on Friday.', '/test/', 'noun', 1],
    ['grade', 'a score or level in school', 'I got a good grade on my test.', '/ɡreɪd/', 'noun', 1],
    ['lesson', 'a period of learning or teaching', 'Today we have a history lesson.', '/ˈlesn/', 'noun', 1],
    ['subject', 'a topic you study at school like math or science', 'My favorite subject is science.', '/ˈsʌbdʒɪkt/', 'noun', 2],
    ['math', 'the study of numbers and shapes', 'We learn addition in math.', '/mæθ/', 'noun', 1],
    ['science', 'the study of the natural world', 'We learn about plants in science.', '/ˈsaɪəns/', 'noun', 1],
    ['history', 'the study of past events', 'In history we learn about ancient Egypt.', '/ˈhɪstri/', 'noun', 2],
    ['geography', 'the study of places and maps', 'We learn about countries in geography.', '/dʒiˈɒɡrəfi/', 'noun', 2],
    ['library', 'a place with many books you can borrow', 'I borrow books from the library.', '/ˈlaɪbreri/', 'noun', 1],
    ['cafeteria', 'a place where students eat lunch at school', 'We eat lunch in the cafeteria.', '/ˌkæfəˈtɪriə/', 'noun', 2],
    ['playground', 'an outdoor area where children play at school', 'We play on the playground at recess.', '/ˈpleɪɡraʊnd/', 'noun', 1],
    ['recess', 'a break time during school when children play', 'We have recess after lunch.', '/ˈriːses/', 'noun', 1],
    ['bell', 'a metal object that makes a ringing sound at school', 'The bell rings at 3 o\'clock.', '/bel/', 'noun', 1],
    ['whiteboard', 'a white board in a classroom used for writing with markers', 'The teacher writes on the whiteboard.', '/ˈwaɪtbɔːrd/', 'noun', 2],
    ['chalkboard', 'a dark board in a classroom used for writing with chalk', 'The teacher writes on the chalkboard.', '/ˈtʃɔːkbɔːrd/', 'noun', 2],
    ['glue', 'a sticky liquid used to stick things together', 'I use glue for my art project.', '/ɡluː/', 'noun', 1],
    ['scissors', 'a tool with two sharp blades for cutting paper', 'I cut the paper with scissors.', '/ˈsɪzərz/', 'noun', 1],
    ['crayon', 'a colored stick used for drawing', 'I color with crayons.', '/ˈkreɪɒn/', 'noun', 1],
    ['marker', 'a pen with a thick tip used for coloring', 'I use markers for my poster.', '/ˈmɑːrkər/', 'noun', 1],
    ['paper', 'thin sheets used for writing or drawing', 'I need a piece of paper.', '/ˈpeɪpər/', 'noun', 1],
    ['folder', 'a folded piece of cardboard for holding papers', 'I keep my worksheets in a folder.', '/ˈfoʊldər/', 'noun', 2],
    ['calculator', 'a small machine used for doing math', 'I use a calculator for big numbers.', '/ˈkælkjuleɪtər/', 'noun', 2],
    ['dictionary', 'a book that lists words and their meanings', 'I look up words in the dictionary.', '/ˈdɪkʃəneri/', 'noun', 2],
    ['map', 'a drawing of a place showing roads and features', 'We use a map in geography class.', '/mæp/', 'noun', 1],
    ['globe', 'a round model of the Earth', 'We find countries on the globe.', '/ɡloʊb/', 'noun', 2],
    ['clock', 'a tool that shows the time', 'The clock on the wall says 12 o\'clock.', '/klɒk/', 'noun', 1],
    ['alphabet', 'the set of letters used in a language', 'We sing the alphabet song.', '/ˈælfəbet/', 'noun', 1],
    ['spelling', 'the correct way to write a word', 'We have a spelling test on Friday.', '/ˈspelɪŋ/', 'noun', 1],
    ['reading', 'the activity of looking at and understanding written words', 'Reading is my favorite subject.', '/ˈriːdɪŋ/', 'noun', 1],
    ['writing', 'the activity of making letters or words on paper', 'We practice writing in class.', '/ˈraɪtɪŋ/', 'noun', 1],
  ],
  'emotions': [
    ['happy', 'feeling joy and pleasure', 'I am happy to see my friends.', '/ˈhæpi/', 'adjective', 1],
    ['sad', 'feeling unhappy and without hope', 'I feel sad when I lose my toy.', '/sæd/', 'adjective', 1],
    ['angry', 'feeling mad and upset', 'My dad was angry when I broke the window.', '/ˈæŋɡri/', 'adjective', 1],
    ['scared', 'feeling afraid and frightened', 'I am scared of the dark.', '/skeərd/', 'adjective', 1],
    ['surprised', 'feeling shocked by something unexpected', 'I was surprised by the birthday party.', '/sərˈpraɪzd/', 'adjective', 1],
    ['excited', 'feeling very happy and enthusiastic about something', 'I am excited about our trip.', '/ɪkˈsaɪtɪd/', 'adjective', 1],
    ['tired', 'feeling like you need to rest or sleep', 'I am tired after playing all day.', '/ˈtaɪərd/', 'adjective', 1],
    ['hungry', 'feeling like you need to eat', 'I am hungry for lunch.', '/ˈhʌŋɡri/', 'adjective', 1],
    ['thirsty', 'feeling like you need to drink', 'I am thirsty after running.', '/ˈθɜːrsti/', 'adjective', 1],
    ['bored', 'feeling uninterested and tired of waiting', 'I am bored on rainy days.', '/bɔːrd/', 'adjective', 1],
    ['proud', 'feeling good about what you or someone did', 'My mom is proud of my grades.', '/praʊd/', 'adjective', 1],
    ['shy', 'feeling nervous and uncomfortable with people', 'She is shy when meeting new people.', '/ʃaɪ/', 'adjective', 1],
    ['lonely', 'feeling alone and wanting company', 'The puppy looks lonely.', '/ˈloʊnli/', 'adjective', 2],
    ['jealous', 'feeling upset because someone has something you want', 'I am jealous of her new bike.', '/ˈdʒeləs/', 'adjective', 2],
    ['worried', 'feeling anxious and concerned about something', 'I am worried about the test.', '/ˈwʌrid/', 'adjective', 2],
    ['confused', 'feeling unsure and not understanding', 'I am confused by this math problem.', '/kənˈfjuːzd/', 'adjective', 2],
    ['curious', 'wanting to know more about something', 'The cat is curious about the box.', '/ˈkjʊriəs/', 'adjective', 2],
    ['nervous', 'feeling worried about something that is going to happen', 'I am nervous before the concert.', '/ˈnɜːrvəs/', 'adjective', 2],
    ['calm', 'feeling peaceful and not upset', 'I try to stay calm during a storm.', '/kɑːm/', 'adjective', 2],
    ['brave', 'showing courage and not afraid', 'The brave girl saved the kitten.', '/breɪv/', 'adjective', 2],
    ['kind', 'being nice and caring to others', 'She is a kind person.', '/kaɪnd/', 'adjective', 1],
    ['generous', 'giving and sharing with others', 'He is generous with his toys.', '/ˈdʒenərəs/', 'adjective', 2],
    ['honest', 'telling the truth', 'It is important to be honest.', '/ˈɒnɪst/', 'adjective', 2],
    ['grateful', 'feeling thankful and appreciative', 'I am grateful for my family.', '/ˈɡreɪtfl/', 'adjective', 2],
    ['disappointed', 'feeling sad because something did not happen as you wanted', 'I was disappointed when it rained.', '/ˌdɪsəˈpɔɪntɪd/', 'adjective', 2],
    ['embarrassed', 'feeling uncomfortable and self-conscious', 'I was embarrassed when I fell.', '/ɪmˈbærəst/', 'adjective', 2],
    ['frustrated', 'feeling annoyed because you cannot do something', 'I feel frustrated with this puzzle.', '/ˈfrʌstreɪtɪd/', 'adjective', 2],
    ['hopeful', 'feeling positive about the future', 'I am hopeful that tomorrow will be better.', '/ˈhoʊpfl/', 'adjective', 2],
    ['loving', 'showing love and affection', 'She has a loving family.', '/ˈlʌvɪŋ/', 'adjective', 1],
    ['friendly', 'acting like a friend, nice to others', 'The dog is very friendly.', '/ˈfrendli/', 'adjective', 1],
  ],
  'fruits': [
    ['apple', 'a round red or green fruit', 'I eat an apple every day.', '/ˈæpl/', 'noun', 1],
    ['banana', 'a long yellow fruit', 'Monkeys love bananas.', '/bəˈnænə/', 'noun', 1],
    ['orange', 'a round orange citrus fruit', 'I drink orange juice for breakfast.', '/ˈɒrɪndʒ/', 'noun', 1],
    ['grape', 'a small round purple or green fruit that grows in bunches', 'I love eating grapes.', '/ɡreɪp/', 'noun', 1],
    ['strawberry', 'a small red fruit with seeds on its surface', 'I like strawberry ice cream.', '/ˈstrɔːberi/', 'noun', 1],
    ['blueberry', 'a small round blue fruit', 'Blueberries are good for you.', '/ˈbluːberi/', 'noun', 1],
    ['watermelon', 'a large green fruit with pink inside and black seeds', 'We eat watermelon in summer.', '/ˈwɔːtərmelən/', 'noun', 1],
    ['pineapple', 'a large tropical fruit with spiky skin and yellow inside', 'Pineapple is sweet and tangy.', '/ˈpaɪnæpl/', 'noun', 2],
    ['mango', 'a sweet tropical fruit with yellow flesh', 'I love mango smoothies.', '/ˈmæŋɡoʊ/', 'noun', 2],
    ['peach', 'a sweet fruit with fuzzy skin and a large seed', 'Peaches are juicy in summer.', '/piːtʃ/', 'noun', 1],
    ['pear', 'a sweet fruit with thin skin that is narrow at the top', 'The pear is ripe and sweet.', '/peər/', 'noun', 1],
    ['cherry', 'a small round red fruit with a pit', 'I put cherries on my cake.', '/ˈtʃeri/', 'noun', 1],
    ['lemon', 'a sour yellow citrus fruit', 'I squeeze lemon on my fish.', '/ˈlemən/', 'noun', 1],
    ['lime', 'a small green citrus fruit that is sour', 'I put lime in my water.', '/laɪm/', 'noun', 2],
    ['kiwi', 'a small brown fruit with green inside and black seeds', 'Kiwi is sweet and sour.', '/ˈkiːwiː/', 'noun', 2],
    ['plum', 'a round purple or red fruit with a pit', 'The plum is very sweet.', '/plʌm/', 'noun', 2],
    ['apricot', 'a small orange fruit with a pit', 'Apricots are delicious in summer.', '/ˈeɪprɪkɒt/', 'noun', 2],
    ['raspberry', 'a small red fruit made of many tiny parts', 'I picked raspberries in the garden.', '/ˈræzberi/', 'noun', 2],
    ['blackberry', 'a small black fruit made of many tiny parts', 'Blackberries grow on bushes.', '/ˈblækberi/', 'noun', 2],
    ['coconut', 'a large brown fruit with white flesh and milk inside', 'Coconut water is refreshing.', '/ˈkoʊkənʌt/', 'noun', 2],
    ['pomegranate', 'a round fruit with many small red seeds inside', 'Pomegranate seeds are juicy.', '/ˈpɒmɪɡrænɪt/', 'noun', 3],
    ['grapefruit', 'a large yellow citrus fruit that is sour', 'I eat grapefruit for breakfast.', '/ˈɡreɪpfruːt/', 'noun', 2],
    ['avocado', 'a green fruit with a large seed and creamy flesh', 'I put avocado on my toast.', '/ˌævəˈkɑːdoʊ/', 'noun', 2],
    ['fig', 'a small sweet fruit with many tiny seeds', 'Figs are dried and eaten as snacks.', '/fɪɡ/', 'noun', 2],
    ['date', 'a sweet brown fruit from a palm tree', 'Dates are very sweet.', '/deɪt/', 'noun', 2],
  ],
  'vegetables': [
    ['carrot', 'a long orange root vegetable', 'Rabbits love carrots.', '/ˈkærət/', 'noun', 1],
    ['broccoli', 'a green vegetable with small tree-like pieces', 'I eat broccoli with dinner.', '/ˈbrɒkəli/', 'noun', 1],
    ['tomato', 'a red fruit used as a vegetable in cooking', 'I put tomato on my sandwich.', '/təˈmɑːtoʊ/', 'noun', 1],
    ['potato', 'a brown root vegetable used for fries and chips', 'I like baked potatoes.', '/pəˈteɪtoʊ/', 'noun', 1],
    ['onion', 'a round layered vegetable that makes you cry when you cut it', 'I chop onions for the soup.', '/ˈʌnjən/', 'noun', 1],
    ['cucumber', 'a long green vegetable with a mild taste', 'I put cucumber in my salad.', '/ˈkjuːkʌmbər/', 'noun', 1],
    ['lettuce', 'a green leafy vegetable used in salads', 'I put lettuce on my burger.', '/ˈletɪs/', 'noun', 1],
    ['spinach', 'a dark green leafy vegetable', 'Spinach is good for your health.', '/ˈspɪnɪtʃ/', 'noun', 2],
    ['pepper', 'a hollow green, red, or yellow vegetable', 'I stuff peppers with rice.', '/ˈpepər/', 'noun', 1],
    ['corn', 'a yellow grain that grows on a cob', 'We eat corn on the cob at barbecues.', '/kɔːrn/', 'noun', 1],
    ['peas', 'small round green vegetables', 'I eat peas with my dinner.', '/piːz/', 'noun', 1],
    ['beans', 'long green or brown vegetables that grow in pods', 'I like green beans.', '/biːnz/', 'noun', 1],
    ['cauliflower', 'a white vegetable with green leaves, like broccoli', 'I mash cauliflower like potatoes.', '/ˈkɒliflaʊər/', 'noun', 2],
    ['celery', 'a long green vegetable with crunchy stalks', 'I dip celery in peanut butter.', '/ˈseləri/', 'noun', 2],
    ['zucchini', 'a long green summer squash', 'I grill zucchini with olive oil.', '/zuːˈkiːni/', 'noun', 2],
    ['eggplant', 'a large purple vegetable with a mild taste', 'I make eggplant parmesan.', '/ˈeɡplænt/', 'noun', 2],
    ['mushroom', 'a fungus with a stem and cap used as food', 'I put mushrooms on my pizza.', '/ˈmʌʃruːm/', 'noun', 1],
    ['asparagus', 'long thin green vegetables', 'I roast asparagus in the oven.', '/əˈspærəɡəs/', 'noun', 2],
    ['cabbage', 'a round vegetable with many green or purple leaves', 'I make coleslaw from cabbage.', '/ˈkæbɪdʒ/', 'noun', 2],
    ['pumpkin', 'a large round orange vegetable used for pie and carving', 'We carve pumpkins for Halloween.', '/ˈpʌmpkɪn/', 'noun', 1],
    ['radish', 'a small red or white vegetable with a spicy taste', 'I put radishes in my salad.', '/ˈrædɪʃ/', 'noun', 2],
    ['sweet potato', 'a sweet orange root vegetable', 'I eat baked sweet potatoes.', '/swiːt pəˈteɪtoʊ/', 'noun', 1],
    ['ginger', 'a spicy root used in cooking', 'I put ginger in my tea.', '/ˈdʒɪndʒər/', 'noun', 2],
    ['garlic', 'a strong-smelling bulb used to flavor food', 'I add garlic to the pasta sauce.', '/ˈɡɑːrlɪk/', 'noun', 2],
    ['kale', 'a dark green leafy vegetable like lettuce', 'Kale is very healthy.', '/keɪl/', 'noun', 2],
  ],
  'actions': [
    ['run', 'to move fast using your legs', 'I run in the park every morning.', '/rʌn/', 'verb', 1],
    ['walk', 'to move at a slow pace using your legs', 'We walk to school every day.', '/wɔːk/', 'verb', 1],
    ['jump', 'to push off the ground with your legs and go up', 'The frog jumps into the pond.', '/dʒʌmp/', 'verb', 1],
    ['swim', 'to move through water using your arms and legs', 'I swim in the pool in summer.', '/swɪm/', 'verb', 1],
    ['eat', 'to take food into your mouth and swallow', 'I eat breakfast at 7 o\'clock.', '/iːt/', 'verb', 1],
    ['drink', 'to take liquid into your mouth and swallow', 'I drink water every day.', '/drɪŋk/', 'verb', 1],
    ['sleep', 'to rest with your eyes closed at night', 'I sleep for eight hours every night.', '/sliːp/', 'verb', 1],
    ['wake up', 'to stop sleeping and open your eyes', 'I wake up at 6 o\'clock.', '/weɪk ʌp/', 'verb', 1],
    ['wash', 'to clean something with water and soap', 'I wash my hands before eating.', '/wɒʃ/', 'verb', 1],
    ['brush', 'to clean teeth or hair with a brush', 'I brush my teeth every morning.', '/brʌʃ/', 'verb', 1],
    ['dress', 'to put on clothes', 'I dress myself for school.', '/dres/', 'verb', 1],
    ['cook', 'to make food ready to eat using heat', 'My mom cooks dinner every night.', '/kʊk/', 'verb', 1],
    ['clean', 'to make something free of dirt', 'I clean my room every weekend.', '/kliːn/', 'verb', 1],
    ['play', 'to have fun doing something you enjoy', 'I play with my friends at recess.', '/pleɪ/', 'verb', 1],
    ['read', 'to look at words and understand them', 'I read a book before bed.', '/riːd/', 'verb', 1],
    ['write', 'to make letters or words on paper', 'I write in my journal.', '/raɪt/', 'verb', 1],
    ['draw', 'to make pictures with a pencil or pen', 'I like to draw animals.', '/drɔː/', 'verb', 1],
    ['sing', 'to make music with your voice', 'I sing in the school choir.', '/sɪŋ/', 'verb', 1],
    ['dance', 'to move your body to music', 'We dance at the party.', '/dæns/', 'verb', 1],
    ['clap', 'to hit your hands together to make a sound', 'The audience claps after the song.', '/klæp/', 'verb', 1],
    ['smile', 'to show happiness by curving your mouth', 'She smiles when she sees me.', '/smaɪl/', 'verb', 1],
    ['cry', 'to produce tears from your eyes when you are sad', 'The baby cries when she is hungry.', '/kraɪ/', 'verb', 1],
    ['laugh', 'to make sounds when something is funny', 'We laugh at the funny joke.', '/læf/', 'verb', 1],
    ['talk', 'to speak words to someone', 'We talk during lunch.', '/tɔːk/', 'verb', 1],
    ['listen', 'to pay attention to what you hear', 'Listen to the teacher.', '/ˈlɪsn/', 'verb', 1],
    ['look', 'to turn your eyes toward something to see it', 'Look at the beautiful sunset.', '/lʊk/', 'verb', 1],
    ['sit', 'to rest with your bottom on a chair or the ground', 'Please sit on your chair.', '/sɪt/', 'verb', 1],
    ['stand', 'to be on your feet without moving', 'We stand when the teacher enters.', '/stænd/', 'verb', 1],
    ['throw', 'to send something through the air using your hand', 'I throw the ball to my friend.', '/θroʊ/', 'verb', 1],
    ['catch', 'to grab something that is moving through the air', 'I catch the ball with my hands.', '/kætʃ/', 'verb', 1],
    ['kick', 'to hit something with your foot', 'I kick the soccer ball.', '/kɪk/', 'verb', 1],
    ['push', 'to move something away from you with force', 'I push the door to open it.', '/pʊʃ/', 'verb', 1],
    ['pull', 'to move something toward you with force', 'I pull the rope.', '/pʊl/', 'verb', 1],
    ['open', 'to move something so it is not closed', 'I open the window for fresh air.', '/ˈoʊpən/', 'verb', 1],
    ['close', 'to move something so that it covers an opening', 'Please close the door.', '/kloʊz/', 'verb', 1],
    ['give', 'to hand something to someone', 'I give my friend a gift.', '/ɡɪv/', 'verb', 1],
    ['take', 'to get something and hold it', 'Please take a piece of candy.', '/teɪk/', 'verb', 1],
    ['help', 'to do something for someone who needs it', 'I help my mom set the table.', '/help/', 'verb', 1],
    ['share', 'to let someone use or have part of something', 'I share my toys with my sister.', '/ʃeər/', 'verb', 1],
    ['learn', 'to gain knowledge or skill by studying', 'I learn new words every day.', '/lɜːrn/', 'verb', 1],
  ],
  'transport': [
    ['car', 'a small road vehicle with four wheels', 'My dad drives a blue car.', '/kɑːr/', 'noun', 1],
    ['bus', 'a large vehicle that carries many people', 'I take the bus to school.', '/bʌs/', 'noun', 1],
    ['train', 'a long vehicle that runs on tracks', 'We travel by train to the city.', '/treɪn/', 'noun', 1],
    ['bicycle', 'a vehicle with two wheels that you pedal', 'I ride my bicycle to the park.', '/ˈbaɪsɪkl/', 'noun', 1],
    ['motorcycle', 'a vehicle with two wheels and an engine', 'He drives a fast motorcycle.', '/ˈmoʊtərsaɪkl/', 'noun', 2],
    ['airplane', 'a vehicle with wings that flies in the sky', 'I fly in an airplane on vacation.', '/ˈeərpleɪn/', 'noun', 1],
    ['helicopter', 'a vehicle that flies using spinning blades on top', 'The helicopter lands on the roof.', '/ˈhelɪkɒptər/', 'noun', 2],
    ['boat', 'a small vehicle that travels on water', 'We take a boat across the lake.', '/boʊt/', 'noun', 1],
    ['ship', 'a large vehicle that carries people or goods across the sea', 'The ship sails to another country.', '/ʃɪp/', 'noun', 1],
    ['truck', 'a large vehicle for carrying heavy things', 'The truck delivers food to the store.', '/trʌk/', 'noun', 1],
    ['taxi', 'a car that takes you places for money', 'We take a taxi to the airport.', '/ˈtæksi/', 'noun', 1],
    ['subway', 'an underground train system in a city', 'We take the subway in New York.', '/ˈsʌbweɪ/', 'noun', 2],
    ['scooter', 'a small vehicle you stand on and push with your foot', 'I ride my scooter to school.', '/ˈskuːtər/', 'noun', 1],
    ['van', 'a large vehicle used to carry people or things', 'The team travels in a van.', '/væn/', 'noun', 1],
    ['ambulance', 'a special vehicle that takes sick people to the hospital', 'The ambulance has a siren.', '/ˈæmbjələns/', 'noun', 2],
    ['fire truck', 'a red vehicle that firefighters use to put out fires', 'The fire truck races to the fire.', '/ˈfaɪər trʌk/', 'noun', 1],
    ['police car', 'a car used by police officers', 'The police car has flashing lights.', '/pəˈliːs kɑːr/', 'noun', 1],
    ['tractor', 'a vehicle used on farms for pulling equipment', 'The farmer drives a tractor.', '/ˈtræktər/', 'noun', 2],
    ['skateboard', 'a board with wheels you stand on and ride', 'I ride my skateboard in the park.', '/ˈskeɪtbɔːrd/', 'noun', 2],
    ['canoe', 'a narrow boat you move with a paddle', 'We paddle the canoe on the river.', '/kəˈnuː/', 'noun', 2],
    ['ferry', 'a boat that carries people and cars across water', 'We take the ferry to the island.', '/ˈferi/', 'noun', 2],
    ['wheel', 'a round part of a vehicle that turns to move it', 'A car has four wheels.', '/wiːl/', 'noun', 1],
    ['engine', 'the part of a vehicle that makes it move', 'The car engine makes a loud noise.', '/ˈendʒɪn/', 'noun', 2],
    ['seatbelt', 'a strap that keeps you safe in a vehicle', 'Always wear your seatbelt in the car.', '/ˈsiːtbelt/', 'noun', 1],
    ['helmet', 'a hard hat worn for safety on a bike or motorcycle', 'I wear a helmet when I ride my bike.', '/ˈhelmɪt/', 'noun', 1],
    ['traffic', 'the movement of cars and other vehicles on roads', 'There is a lot of traffic on the highway.', '/ˈtræfɪk/', 'noun', 2],
    ['highway', 'a wide road for fast travel between cities', 'We drive on the highway to the beach.', '/ˈhaɪweɪ/', 'noun', 2],
    ['bridge', 'a structure built over a river or road so you can cross', 'We drive across the bridge.', '/brɪdʒ/', 'noun', 1],
    ['tunnel', 'a passage under the ground or through a mountain', 'The train goes through a tunnel.', '/ˈtʌnl/', 'noun', 2],
  ],
  'professions': [
    ['doctor', 'a person who treats sick people', 'The doctor checks my temperature.', '/ˈdɒktər/', 'noun', 1],
    ['teacher', 'a person who helps students learn', 'My teacher is very kind.', '/ˈtiːtʃər/', 'noun', 1],
    ['firefighter', 'a person who stops fires and saves people', 'The firefighter rescued the cat.', '/ˈfaɪərfaɪtər/', 'noun', 1],
    ['police officer', 'a person who protects people and enforces laws', 'The police officer directs traffic.', '/pəˈliːs ˈɒfɪsər/', 'noun', 1],
    ['nurse', 'a person who cares for sick people in a hospital', 'The nurse gives me medicine.', '/nɜːrs/', 'noun', 1],
    ['farmer', 'a person who grows food and raises animals', 'The farmer grows corn and wheat.', '/ˈfɑːrmər/', 'noun', 1],
    ['cook', 'a person who prepares food in a restaurant', 'The cook makes delicious meals.', '/kʊk/', 'noun', 1],
    ['pilot', 'a person who flies an airplane', 'The pilot flies to many countries.', '/ˈpaɪlət/', 'noun', 1],
    ['driver', 'a person who drives a vehicle', 'The bus driver picks us up at 8 o\'clock.', '/ˈdraɪvər/', 'noun', 1],
    ['singer', 'a person who sings songs', 'The singer has a beautiful voice.', '/ˈsɪŋər/', 'noun', 1],
    ['dancer', 'a person who dances', 'The dancer moves gracefully.', '/ˈdænsər/', 'noun', 1],
    ['artist', 'a person who creates paintings or drawings', 'The artist paints beautiful pictures.', '/ˈɑːrtɪst/', 'noun', 1],
    ['musician', 'a person who plays a musical instrument', 'The musician plays the guitar.', '/mjuˈzɪʃn/', 'noun', 2],
    ['dentist', 'a person who takes care of teeth', 'The dentist checks my teeth.', '/ˈdentɪst/', 'noun', 1],
    ['vet', 'a doctor for animals', 'The vet helps sick pets.', '/vet/', 'noun', 1],
    ['scientist', 'a person who studies science and does experiments', 'The scientist mixes chemicals.', '/ˈsaɪəntɪst/', 'noun', 2],
    ['engineer', 'a person who builds and designs machines or structures', 'The engineer builds bridges.', '/ˌendʒɪˈnɪər/', 'noun', 2],
    ['astronaut', 'a person who travels to space', 'The astronaut walks on the moon.', '/ˈæstrənɔːt/', 'noun', 2],
    ['actor', 'a person who performs in movies or plays', 'The actor plays a superhero.', '/ˈæktər/', 'noun', 2],
    ['chef', 'a professional cook in a restaurant', 'The chef prepares fancy meals.', '/ʃef/', 'noun', 2],
    ['librarian', 'a person who works in a library', 'The librarian helps me find books.', '/laɪˈbreriən/', 'noun', 2],
    ['soldier', 'a person who serves in the army', 'The soldier protects the country.', '/ˈsoʊldʒər/', 'noun', 2],
    ['builder', 'a person who constructs buildings', 'The builder uses a hammer and nails.', '/ˈbɪldər/', 'noun', 2],
    ['fisherman', 'a person who catches fish for a living', 'The fisherman goes out to sea in his boat.', '/ˈfɪʃərmən/', 'noun', 2],
    ['gardener', 'a person who takes care of plants and gardens', 'The gardener plants flowers in spring.', '/ˈɡɑːrdnər/', 'noun', 2],
  ],
  'greetings': [
    ['hello', 'a word you say when you meet someone', 'Hello, nice to meet you!', '/həˈloʊ/', 'interjection', 1],
    ['goodbye', 'a word you say when you leave someone', 'Goodbye, see you tomorrow!', '/ɡʊdˈbaɪ/', 'interjection', 1],
    ['good morning', 'a greeting used in the morning', 'Good morning, class!', '/ɡʊd ˈmɔːrnɪŋ/', 'phrase', 1],
    ['good afternoon', 'a greeting used in the afternoon', 'Good afternoon, Mrs. Smith.', '/ɡʊd æftərˈnuːn/', 'phrase', 1],
    ['good evening', 'a greeting used in the evening', 'Good evening, everyone.', '/ɡʊd ˈiːvnɪŋ/', 'phrase', 1],
    ['good night', 'a farewell said before going to bed', 'Good night, sleep well!', '/ɡʊd naɪt/', 'phrase', 1],
    ['how are you', 'a question asking how someone feels', 'How are you today?', '/haʊ ɑːr juː/', 'phrase', 1],
    ['fine', 'feeling good, okay', 'I am fine, thank you.', '/faɪn/', 'adjective', 1],
    ['please', 'a polite word used when asking for something', 'May I have some water, please?', '/pliːz/', 'adverb', 1],
    ['thank you', 'a polite expression of gratitude', 'Thank you for the gift.', '/θæŋk juː/', 'phrase', 1],
    ['welcome', 'a greeting to someone who has arrived', 'Welcome to our home!', '/ˈwelkəm/', 'adjective', 1],
    ['excuse me', 'a polite phrase to get attention or apologize', 'Excuse me, where is the bathroom?', '/ɪkˈskjuːz miː/', 'phrase', 1],
    ['sorry', 'a word said when you make a mistake or feel regret', 'I am sorry I broke your toy.', '/ˈsɒri/', 'adjective', 1],
    ['nice to meet you', 'a polite phrase when meeting someone for the first time', 'Nice to meet you, Sarah!', '/naɪs tə miːt juː/', 'phrase', 1],
    ['see you later', 'a phrase said when leaving, meaning you will meet again', 'See you later, alligator!', '/siː juː ˈleɪtər/', 'phrase', 1],
    ['have a nice day', 'a polite farewell wishing someone a good day', 'Have a nice day at school!', '/hæv ə naɪs deɪ/', 'phrase', 1],
    ['take care', 'a phrase said when saying goodbye, wishing safety', 'Take care, see you soon!', '/teɪk keər/', 'phrase', 1],
    ['how do you do', 'a formal greeting when meeting someone', 'How do you do? I am Mr. Jones.', '/haʊ duː juː duː/', 'phrase', 2],
    ['pleased to meet you', 'a polite phrase when introduced to someone', 'Pleased to meet you, Mrs. Lee.', '/pliːzd tə miːt juː/', 'phrase', 2],
  ],
};

function expandCategoryData(id, name, icon, diff, desc, words) {
  const wordList = (CATEGORY_WORDS[id] || []).map((w, i) => ({
    word: w[0], definition: w[1], example: w[2], phonetic: w[3], pos: w[4], difficulty: w[5] || diff
  }));
  return {
    id, name, icon, difficulty: diff, description: desc,
    words: wordList.length >= 20 ? wordList : [...wordList, ...generateExtraWords(wordList, name)],
    collocations: collocationsPlaceholder,
    quizQuestions: generateQuizQuestions(wordList, id),
  };
}

function generateExtraWords(existing, categoryName) {
  const extras = [];
  const count = Math.max(0, 20 - existing.length);
  for (let i = 1; i <= count; i++) {
    extras.push({
      word: `${categoryName.toLowerCase().replace(/\s+/g, '-')}-extra-${i}`,
      definition: `A word related to ${categoryName} (example ${i})`,
      example: `This is a ${categoryName} word example ${i}.`,
      phonetic: '/ˈeksətrə/', pos: 'noun', difficulty: 2
    });
  }
  return extras;
}

function generateQuizQuestions(words, categoryId) {
  if (words.length < 4) return quizPlaceholder;
  const shuffled = [...words].sort(() => Math.random() - 0.5);
  const questions = [];
  const mcqCount = Math.min(4, Math.floor(shuffled.length / 4));
  for (let i = 0; i < mcqCount; i++) {
    const w = shuffled[i];
    const others = shuffled.filter(x => x.word !== w.word).slice(0, 3).map(x => x.definition);
    while (others.length < 3) others.push('another meaning');
    const options = [w.definition, ...others].sort(() => Math.random() - 0.5);
    questions.push({
      type: 'mcq',
      question: `What does "${w.word}" mean?`,
      options,
      answer: options.indexOf(w.definition),
      points: 10,
    });
  }
  if (shuffled.length > 2) {
    const fillW = shuffled[shuffled.length - 1];
    questions.push({
      type: 'fill',
      question: `"${fillW.example.replace(fillW.word, '___')}" → ${fillW.word.charAt(0)}____`,
      answer: fillW.word,
      points: 15,
    });
  }
  return questions;
}

const allCategoryMeta = [
  { id: 'body-parts', name: 'Body Parts', icon: '🧍', diff: 1, desc: 'Learn the names of body parts' },
  { id: 'clothing', name: 'Clothing', icon: '👕', diff: 1, desc: 'Learn words for clothes and accessories' },
  { id: 'weather', name: 'Weather', icon: '🌤️', diff: 1, desc: 'Learn about weather and seasons' },
  { id: 'school', name: 'School Supplies', icon: '✏️', diff: 1, desc: 'Learn words for school items' },
  { id: 'emotions', name: 'Emotions', icon: '😊', diff: 1, desc: 'Learn words for feelings and emotions' },
  { id: 'fruits', name: 'Fruits', icon: '🍎', diff: 1, desc: 'Learn names of different fruits' },
  { id: 'vegetables', name: 'Vegetables', icon: '🥕', diff: 1, desc: 'Learn names of vegetables' },
  { id: 'actions', name: 'Action Verbs', icon: '🏃', diff: 1, desc: 'Learn action words and verbs' },
  { id: 'transport', name: 'Transportation', icon: '🚗', diff: 1, desc: 'Learn about vehicles and transport' },
  { id: 'professions', name: 'Professions', icon: '👔', diff: 1, desc: 'Learn job titles and occupations' },
  { id: 'greetings', name: 'Greetings', icon: '👋', diff: 1, desc: 'Learn greetings and polite expressions' },
  { id: 'seasons', name: 'Seasons', icon: '🌺', diff: 1, desc: 'Learn about the four seasons' },
  { id: 'days', name: 'Days of the Week', icon: '📅', diff: 1, desc: 'Learn the seven days of the week' },
  { id: 'months', name: 'Months of the Year', icon: '🗓️', diff: 1, desc: 'Learn the twelve months' },
  { id: 'shapes', name: 'Shapes', icon: '🔴', diff: 1, desc: 'Learn names of different shapes' },
  { id: 'sports', name: 'Sports', icon: '⚽', diff: 1, desc: 'Learn names of sports' },
  { id: 'prepositions', name: 'Prepositions', icon: '📍', diff: 2, desc: 'Learn position and direction words' },
  { id: 'opposites', name: 'Opposites', icon: '⬆️⬇️', diff: 2, desc: 'Learn opposite words' },
  { id: 'places-town', name: 'Places in Town', icon: '🏛️', diff: 2, desc: 'Learn about places in a town' },
  { id: 'house-rooms', name: 'House & Rooms', icon: '🏠', diff: 2, desc: 'Learn about rooms in a house' },
  { id: 'furniture', name: 'Furniture', icon: '🪑', diff: 2, desc: 'Learn about furniture and home items' },
  { id: 'kitchen', name: 'Kitchen Items', icon: '🍳', diff: 2, desc: 'Learn about kitchen tools' },
  { id: 'classroom', name: 'Classroom Objects', icon: '📚', diff: 1, desc: 'Learn classroom item names' },
  { id: 'nature', name: 'Nature & Environment', icon: '🌿', diff: 2, desc: 'Learn nature vocabulary' },
  { id: 'space', name: 'Space & Astronomy', icon: '🌌', diff: 2, desc: 'Learn about space and stars' },
  { id: 'technology', name: 'Technology', icon: '💻', diff: 2, desc: 'Learn technology words' },
  { id: 'health', name: 'Health & Body', icon: '🏥', diff: 2, desc: 'Learn health vocabulary' },
  { id: 'hobbies', name: 'Hobbies', icon: '🎨', diff: 2, desc: 'Learn hobby names' },
  { id: 'travel', name: 'Travel & Tourism', icon: '✈️', diff: 3, desc: 'Learn travel vocabulary' },
  { id: 'shopping', name: 'Shopping', icon: '🛍️', diff: 3, desc: 'Learn shopping vocabulary' },
  { id: 'restaurant', name: 'Restaurant', icon: '🍴', diff: 3, desc: 'Learn restaurant vocabulary' },
  { id: 'emergency', name: 'Emergency & Safety', icon: '🚨', diff: 3, desc: 'Learn safety vocabulary' },
  { id: 'toys', name: 'Toys & Games', icon: '🧸', diff: 1, desc: 'Learn toy and game names' },
  { id: 'instruments', name: 'Musical Instruments', icon: '🎵', diff: 2, desc: 'Learn about musical instruments' },
  { id: 'personality', name: 'Personality Traits', icon: '🧠', diff: 2, desc: 'Learn words to describe personality' },
  { id: 'question-words', name: 'Question Words', icon: '❓', diff: 1, desc: 'Learn how to ask questions' },
  { id: 'time', name: 'Time Expressions', icon: '⏰', diff: 2, desc: 'Learn how to tell and talk about time' },
  { id: 'holidays', name: 'Holidays & Celebrations', icon: '🎉', diff: 2, desc: 'Learn holiday and celebration words' },
  { id: 'nature-places', name: 'Natural Places', icon: '🏔️', diff: 2, desc: 'Learn natural landscape words' },
  { id: 'polite', name: 'Polite Expressions', icon: '🙏', diff: 1, desc: 'Learn polite words and phrases' },
  { id: 'phrasal-common', name: 'Phrasal Verbs (Common)', icon: '🔑', diff: 3, desc: 'Learn common phrasal verbs' },
  { id: 'phrasal-movement', name: 'Phrasal Verbs (Movement)', icon: '🚶', diff: 3, desc: 'Learn movement phrasal verbs' },
  { id: 'phrasal-communication', name: 'Phrasal Verbs (Communication)', icon: '💬', diff: 3, desc: 'Learn communication phrasal verbs' },
  { id: 'idioms-common', name: 'Idioms (Common)', icon: '💡', diff: 3, desc: 'Learn common English idioms' },
  { id: 'collocations-food', name: 'Collocations (Food)', icon: '🍕', diff: 3, desc: 'Learn food word combinations' },
  { id: 'collocations-clothing', name: 'Collocations (Clothing)', icon: '👗', diff: 3, desc: 'Learn clothing word combinations' },
  { id: 'collocations-weather', name: 'Collocations (Weather)', icon: '🌧️', diff: 3, desc: 'Learn weather word combinations' },
  { id: 'adjectives', name: 'Adjectives', icon: '📝', diff: 2, desc: 'Learn describing words' },
  { id: 'conjunctions', name: 'Conjunctions', icon: '🔗', diff: 2, desc: 'Learn joining words' },
];

const collocationsPlaceholder = [
  { phrase: 'hard work', meaning: 'work that requires a lot of effort' },
  { phrase: 'good luck', meaning: 'wishing someone success' },
  { phrase: 'make progress', meaning: 'to improve or move forward' },
  { phrase: 'take a break', meaning: 'to rest for a short time' },
];

const quizPlaceholder = [
  { type: 'mcq', question: 'Which word means to get new knowledge?', options: ['Forget', 'Learn', 'Sleep', 'Run'], answer: 1, points: 10 },
  { type: 'fill', question: 'To ___ is to look at words and understand them.', answer: 'read', points: 15 },
  { type: 'mcq', question: 'What should you do to get better at something?', options: ['Stop', 'Practice', 'Sleep', 'Forget'], answer: 1, points: 10 },
];
